//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batches
    {
        public string Matnr { get; set; }
        public string Werks { get; set; }
        public string Charg { get; set; }
        public System.DateTime LastSyncTimestamp { get; set; }
        public Nullable<System.DateTime> Ersda { get; set; }
        public Nullable<System.DateTime> Vfdat { get; set; }
    }
}
