//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_CargaExcel_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BG_CargaExcel_Items()
        {
            this.BG_CargaExcel_DatosMensuales = new HashSet<BG_CargaExcel_DatosMensuales>();
            this.BG_CargaExcel_ResumenPeriodo = new HashSet<BG_CargaExcel_ResumenPeriodo>();
        }
    
        public int ID_Item { get; set; }
        public int ID_Carga { get; set; }
        public Nullable<int> Item_No { get; set; }
        public string Vehicle { get; set; }
        public string SAP_Invoice_Code { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<System.DateTime> Inicio_Demanda { get; set; }
        public Nullable<System.DateTime> Fin_Demanda { get; set; }
        public string Business_And_Plant { get; set; }
        public string Business { get; set; }
        public string Previous_SAP_Invoice_Code { get; set; }
        public string Mnemonic_Vehicle_Plant { get; set; }
        public string Invoiced_To { get; set; }
        public string SAP_Client_Number { get; set; }
        public string Shipped_To { get; set; }
        public string Own_CM { get; set; }
        public string Route { get; set; }
        public string Plant_Number { get; set; }
        public string External_Processor { get; set; }
        public string Mill { get; set; }
        public string SAP_Master_Coil { get; set; }
        public string Part_Description { get; set; }
        public string Part_Number { get; set; }
        public string Production_Line { get; set; }
        public string Production_Nameplate { get; set; }
        public string Propulsion_System_Type { get; set; }
        public string OEM { get; set; }
        public Nullable<double> Parts_Auto { get; set; }
        public Nullable<double> Stroke_Auto { get; set; }
        public string Material_Type { get; set; }
        public string Material { get; set; }
        public string Shape { get; set; }
        public Nullable<double> Initial_Weight_Part_KG { get; set; }
        public Nullable<double> Net_Weight_Part_KG { get; set; }
        public Nullable<double> Eng_Scrap_Part_KG { get; set; }
        public Nullable<bool> Scrap_Consolidation { get; set; }
        public Nullable<double> Ventas_Part_USD { get; set; }
        public Nullable<double> Material_Cost_Part_USD { get; set; }
        public Nullable<double> Cost_Outside_Proccessor_USD { get; set; }
        public Nullable<double> VAS_Part_USD { get; set; }
        public Nullable<double> Additional_Material_Cost_Part_USD { get; set; }
        public Nullable<double> Outgoing_Freight_PART_USD { get; set; }
        public string Trans_Silao_SLP { get; set; }
        public Nullable<double> Vas_TO { get; set; }
        public string Freights_Income { get; set; }
        public string Outgoing_Freight { get; set; }
        public string Coils_And_Slitter { get; set; }
        public Nullable<bool> Additional_Processes { get; set; }
        public string Production_Processes { get; set; }
        public Nullable<double> Freights_Income_USD_Per_Part { get; set; }
        public Nullable<double> Maniobras_USD_Per_Part { get; set; }
        public Nullable<double> Customs_Expenses_USD_Per_Part { get; set; }
        public Nullable<double> Wooden_Pallets_USD_Per_Part { get; set; }
        public Nullable<double> Standard_Packaging_USD_Per_Part { get; set; }
        public Nullable<double> Plastic_Strips_USD_Per_Part { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_CargaExcel_DatosMensuales> BG_CargaExcel_DatosMensuales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_CargaExcel_ResumenPeriodo> BG_CargaExcel_ResumenPeriodo { get; set; }
        public virtual BG_CargaExcel_Cargas BG_CargaExcel_Cargas { get; set; }
    }
}
