//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_CargaExcel_DatosMensuales
    {
        public long ID_DatoMensual { get; set; }
        public int ID_Item { get; set; }
        public int ID_AnioFiscal { get; set; }
        public int ID_Metrica { get; set; }
        public int Anio { get; set; }
        public int Mes { get; set; }
        public decimal Valor { get; set; }
    
        public virtual BG_CargaExcel_AniosFiscales BG_CargaExcel_AniosFiscales { get; set; }
        public virtual BG_CargaExcel_Items BG_CargaExcel_Items { get; set; }
        public virtual BG_CargaExcel_Metricas BG_CargaExcel_Metricas { get; set; }
    }
}
