//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_Forecast_cat_historico_scrap
    {
        public int id { get; set; }
        public int id_planta { get; set; }
        public string tipo_metal { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<double> scrap { get; set; }
        public double scrap_ganancia { get; set; }
    
        public virtual plantas plantas { get; set; }
    }
}
