//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_Forecast_item
    {
        public int id { get; set; }
        public int id_bg_forecast_reporte { get; set; }
        public Nullable<int> id_ihs_item { get; set; }
        public Nullable<int> id_ihs_combinacion { get; set; }
        public Nullable<int> id_ihs_rel_division { get; set; }
        public int pos { get; set; }
        public string business_and_plant { get; set; }
        public bool calculo_activo { get; set; }
        public string sap_invoice_code { get; set; }
        public string invoiced_to { get; set; }
        public string number_sap_client { get; set; }
        public string shipped_to { get; set; }
        public string own_cm { get; set; }
        public string route { get; set; }
        public string plant { get; set; }
        public string external_processor { get; set; }
        public string mill { get; set; }
        public string sap_master_coil { get; set; }
        public string part_description { get; set; }
        public string part_number { get; set; }
        public string production_line { get; set; }
        public string vehicle { get; set; }
        public Nullable<double> parts_auto { get; set; }
        public Nullable<double> strokes_auto { get; set; }
        public string material_type { get; set; }
        public string shape { get; set; }
        public Nullable<double> initial_weight_part { get; set; }
        public Nullable<double> net_weight_part { get; set; }
        public bool scrap_consolidation { get; set; }
        public Nullable<double> ventas_part { get; set; }
        public Nullable<double> material_cost_part { get; set; }
        public Nullable<double> cost_of_outside_processor { get; set; }
        public Nullable<double> additional_material_cost_part { get; set; }
        public Nullable<double> outgoing_freight_part { get; set; }
        public string freights_income { get; set; }
        public string outgoing_freight { get; set; }
        public string cat_1 { get; set; }
        public string cat_2 { get; set; }
        public string cat_3 { get; set; }
        public string cat_4 { get; set; }
        public Nullable<double> freights_income_usd_part { get; set; }
        public Nullable<double> maniobras_usd_part { get; set; }
        public Nullable<double> customs_expenses { get; set; }
        public string previous_sap_invoice_code { get; set; }
        public string mnemonic_vehicle_plant { get; set; }
        public string propulsion_system_type { get; set; }
        public string trans_silao_slp { get; set; }
        public Nullable<double> wooden_pallet_usd_part { get; set; }
        public Nullable<double> packaging_price_usd_part { get; set; }
        public Nullable<double> neopreno_usd_part { get; set; }
        public Nullable<int> id_ihs_custom { get; set; }
    
        public virtual BG_Forecast_reporte BG_Forecast_reporte { get; set; }
        public virtual BG_IHS_combinacion BG_IHS_combinacion { get; set; }
        public virtual BG_ihs_vehicle_custom BG_ihs_vehicle_custom { get; set; }
        public virtual BG_IHS_rel_division BG_IHS_rel_division { get; set; }
        public virtual BG_IHS_item BG_IHS_item { get; set; }
    }
}
