//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_forecast_cat_historico_ventas
    {
        public int id { get; set; }
        public int id_cliente { get; set; }
        public int id_seccion { get; set; }
        public System.DateTime fecha { get; set; }
        public double valor { get; set; }
    
        public virtual BG_forecast_cat_clientes BG_forecast_cat_clientes { get; set; }
        public virtual BG_Forecast_cat_secciones_calculo BG_Forecast_cat_secciones_calculo { get; set; }
    }
}
