//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_IHS_versiones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BG_IHS_versiones()
        {
            this.BG_Forecast_reporte = new HashSet<BG_Forecast_reporte>();
            this.BG_IHS_plantas = new HashSet<BG_IHS_plantas>();
            this.BG_IHS_regiones = new HashSet<BG_IHS_regiones>();
            this.BG_IHS_rel_regiones = new HashSet<BG_IHS_rel_regiones>();
            this.BG_IHS_segmentos = new HashSet<BG_IHS_segmentos>();
            this.BG_IHS_combinacion = new HashSet<BG_IHS_combinacion>();
            this.BG_IHS_division = new HashSet<BG_IHS_division>();
            this.BG_IHS_item = new HashSet<BG_IHS_item>();
        }
    
        public int id { get; set; }
        public System.DateTime periodo { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_Forecast_reporte> BG_Forecast_reporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_IHS_plantas> BG_IHS_plantas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_IHS_regiones> BG_IHS_regiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_IHS_rel_regiones> BG_IHS_rel_regiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_IHS_segmentos> BG_IHS_segmentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_IHS_combinacion> BG_IHS_combinacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_IHS_division> BG_IHS_division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_IHS_item> BG_IHS_item { get; set; }
    }
}
