//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_ihs_vehicle_custom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BG_ihs_vehicle_custom()
        {
            this.BG_Forecast_item = new HashSet<BG_Forecast_item>();
            this.BG_IHS_custom_rel_demanda = new HashSet<BG_IHS_custom_rel_demanda>();
        }
    
        public int Id { get; set; }
        public string MnemonicVehiclePlant { get; set; }
        public string ProductionPlant { get; set; }
        public string ManufacturerGroup { get; set; }
        public System.DateTime sop_start_of_production { get; set; }
        public System.DateTime eop_end_of_production { get; set; }
        public string Vehicle { get; set; }
        public string AssemblyType { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_Forecast_item> BG_Forecast_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_IHS_custom_rel_demanda> BG_IHS_custom_rel_demanda { get; set; }
    }
}
