//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_IHS_combinacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BG_IHS_combinacion()
        {
            this.BG_IHS_rel_combinacion = new HashSet<BG_IHS_rel_combinacion>();
            this.BG_Forecast_item = new HashSet<BG_Forecast_item>();
        }
    
        public int id { get; set; }
        public int id_ihs_version { get; set; }
        public string vehicle { get; set; }
        public string production_brand { get; set; }
        public string production_plant { get; set; }
        public string manufacturer_group { get; set; }
        public Nullable<System.DateTime> sop_start_of_production { get; set; }
        public Nullable<System.DateTime> eop_end_of_production { get; set; }
        public string comentario { get; set; }
        public Nullable<decimal> porcentaje_scrap { get; set; }
        public bool activo { get; set; }
        public string production_nameplate { get; set; }
    
        public virtual BG_IHS_versiones BG_IHS_versiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_IHS_rel_combinacion> BG_IHS_rel_combinacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_Forecast_item> BG_Forecast_item { get; set; }
    }
}
