//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_IHS_division
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BG_IHS_division()
        {
            this.BG_IHS_rel_division = new HashSet<BG_IHS_rel_division>();
        }
    
        public int id { get; set; }
        public int id_ihs_item { get; set; }
        public string comentario { get; set; }
        public Nullable<decimal> porcentaje_scrap { get; set; }
        public bool activo { get; set; }
    
        public virtual BG_IHS_item BG_IHS_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_IHS_rel_division> BG_IHS_rel_division { get; set; }
    }
}
