//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_IHS_regiones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BG_IHS_regiones()
        {
            this.BG_IHS_rel_regiones = new HashSet<BG_IHS_rel_regiones>();
        }
    
        public int id { get; set; }
        public int id_ihs_version { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
    
        public virtual BG_IHS_versiones BG_IHS_versiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BG_IHS_rel_regiones> BG_IHS_rel_regiones { get; set; }
    }
}
