//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_IHS_rel_combinacion
    {
        public int id { get; set; }
        public int id_ihs_combinacion { get; set; }
        public int id_ihs_item { get; set; }
    
        public virtual BG_IHS_item BG_IHS_item { get; set; }
        public virtual BG_IHS_combinacion BG_IHS_combinacion { get; set; }
    }
}
