//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;

    public partial class bom_en_sap : IEquatable<bom_en_sap>
    {
        public string Material { get; set; }
        public string Plnt { get; set; }
        public string BOM { get; set; }
        public string AltBOM { get; set; }
        public string Item { get; set; }
        public string Component { get; set; }
        public string Created_by { get; set; }
        public string BOM1 { get; set; }
        public string Node { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Un { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public bool activo { get; set; }

        //para realizar la comparacion    

        public bool Equals(bom_en_sap other)
        {
            if (other is null)
                return false;

            return this.Material == other.Material
                && this.Plnt == other.Plnt
                && this.BOM == other.BOM
                && this.AltBOM == other.AltBOM
                && this.Item == other.Item
                && this.Component == other.Component
                && this.Created_by == other.Created_by
                && this.BOM1 == other.BOM1
                && this.Node == other.Node
                && this.Quantity == other.Quantity
                && this.Un == other.Un
                && this.Created == other.Created
                && this.activo == other.activo
                ;
        }

        public override bool Equals(object obj) => Equals(obj as bom_en_sap);
        public override int GetHashCode() => (Material, Plnt, BOM, AltBOM, Item).GetHashCode();
    }
}
