//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bom_en_sap
    {
        public string Material { get; set; }
        public string Plnt { get; set; }
        public string BOM { get; set; }
        public string AltBOM { get; set; }
        public string Item { get; set; }
        public string Component { get; set; }
        public string Created_by { get; set; }
        public string BOM1 { get; set; }
        public string Node { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Un { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public bool activo { get; set; }
        public Nullable<System.DateTime> LastDateUsed { get; set; }
    }
}
