//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class budget_conceptos_mantenimiento
    {
        public int id { get; set; }
        public int id_rel_fy_cc { get; set; }
        public int id_cuenta_sap { get; set; }
        public int mes { get; set; }
        public string moneda { get; set; }
        public double gasto { get; set; }
        public Nullable<double> one_time { get; set; }
    
        public virtual budget_rel_fy_centro budget_rel_fy_centro { get; set; }
        public virtual budget_cuenta_sap budget_cuenta_sap { get; set; }
    }
}
