//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class budget_cantidad
    {
        public int id { get; set; }
        public int id_budget_rel_fy_centro { get; set; }
        public int id_cuenta_sap { get; set; }
        public int mes { get; set; }
        public string currency_iso { get; set; }
        public decimal cantidad { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual budget_cuenta_sap budget_cuenta_sap { get; set; }
        public virtual budget_rel_fy_centro budget_rel_fy_centro { get; set; }
    }
}
