//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class budget_rel_fy_centro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public budget_rel_fy_centro()
        {
            this.budget_cantidad = new HashSet<budget_cantidad>();
            this.budget_conceptos_mantenimiento = new HashSet<budget_conceptos_mantenimiento>();
            this.budget_rel_comentarios = new HashSet<budget_rel_comentarios>();
            this.budget_rel_documento = new HashSet<budget_rel_documento>();
            this.budget_cantidad_forecast = new HashSet<budget_cantidad_forecast>();
        }
    
        public int id { get; set; }
        public int id_anio_fiscal { get; set; }
        public int id_centro_costo { get; set; }
        public bool estatus { get; set; }
    
        public virtual budget_anio_fiscal budget_anio_fiscal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<budget_cantidad> budget_cantidad { get; set; }
        public virtual budget_centro_costo budget_centro_costo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<budget_conceptos_mantenimiento> budget_conceptos_mantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<budget_rel_comentarios> budget_rel_comentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<budget_rel_documento> budget_rel_documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<budget_cantidad_forecast> budget_cantidad_forecast { get; set; }
    }
}
