//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class budget_rel_conceptos_cantidades
    {
        public int id { get; set; }
        public int id_budget_cantidad { get; set; }
        public int id_rel_conceptos { get; set; }
        public Nullable<double> cantidad { get; set; }
    
        public virtual budget_cantidad budget_cantidad { get; set; }
        public virtual budget_rel_conceptos_formulas budget_rel_conceptos_formulas { get; set; }
    }
}
