//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class budget_anio_fiscal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public budget_anio_fiscal()
        {
            this.budget_rel_fy_centro = new HashSet<budget_rel_fy_centro>();
            this.budget_rel_tipo_cambio_fy = new HashSet<budget_rel_tipo_cambio_fy>();
            this.budget_target = new HashSet<budget_target>();
            this.budget_rel_tipo_cambio_fy_forecast = new HashSet<budget_rel_tipo_cambio_fy_forecast>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public int anio_inicio { get; set; }
        public int mes_inicio { get; set; }
        public int anio_fin { get; set; }
        public int mes_fin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<budget_rel_fy_centro> budget_rel_fy_centro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<budget_rel_tipo_cambio_fy> budget_rel_tipo_cambio_fy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<budget_target> budget_target { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<budget_rel_tipo_cambio_fy_forecast> budget_rel_tipo_cambio_fy_forecast { get; set; }
    }
}
