//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CI_conteo_inventario
    {
        public int id { get; set; }
        public string centro { get; set; }
        public string almacen { get; set; }
        public string ubicacion { get; set; }
        public string articulo { get; set; }
        public string material { get; set; }
        public string lote { get; set; }
        public string no_bobina { get; set; }
        public Nullable<double> sap_cantidad { get; set; }
        public Nullable<double> libre_utilizacion { get; set; }
        public Nullable<double> bloqueado { get; set; }
        public Nullable<double> control_calidad { get; set; }
        public string unidad_base_medida { get; set; }
        public Nullable<double> altura { get; set; }
        public Nullable<double> espesor { get; set; }
        public Nullable<double> peso { get; set; }
    }
}
