//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_v3 : IEquatable<class_v3>
    {
        public string Object { get; set; }
        public string Grade { get; set; }
        public string Customer { get; set; }
        public string Shape { get; set; }
        public string Customer_part_number { get; set; }
        public string Surface { get; set; }
        public string Gauge___Metric { get; set; }
        public string Mill { get; set; }
        public string Width___Metr { get; set; }
        public string Length_mm_ { get; set; }
        public bool activo { get; set; }

        //para realizar la comparacion    

        public bool Equals(class_v3 other)
        {
            if (other is null)
                return false;

            return
                this.Object == other.Object
                    && this.Grade == other.Grade
                    && this.Customer == other.Customer
                    && this.Shape == other.Shape
                    && this.Customer_part_number == other.Customer_part_number
                    && this.Surface == other.Surface
                    && this.Gauge___Metric == other.Gauge___Metric
                    && this.Mill == other.Mill
                    && this.Width___Metr == other.Width___Metr
                    && this.Length_mm_ == other.Length_mm_
                    && this.activo == other.activo
                ;
        }

        public override bool Equals(object obj) => Equals(obj as class_v3);
        public override int GetHashCode() => (Object).GetHashCode();
    }
}
