//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Assignment_Activity
    {
        public int ID_AssignmentActivity { get; set; }
        public int ID_Assignment { get; set; }
        public int ID_Activity { get; set; }
        public bool IsComplete { get; set; }
    
        public virtual CTZ_Project_Assignment CTZ_Project_Assignment { get; set; }
        public virtual CTZ_Department_Activity CTZ_Department_Activity { get; set; }
    }
}
