//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTZ_Clients()
        {
            this.CTZ_Projects = new HashSet<CTZ_Projects>();
        }
    
        public int ID_Cliente { get; set; }
        public string Client_Name { get; set; }
        public string Clave_SAP { get; set; }
        public string Pais { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Codigo_Postal { get; set; }
        public string Calle { get; set; }
        public string Estado { get; set; }
        public bool Automotriz { get; set; }
        public string Telephone { get; set; }
        public bool Active { get; set; }
        public Nullable<int> ID_Country { get; set; }
        public string ShortName { get; set; }
    
        public virtual CTZ_Countries CTZ_Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Projects> CTZ_Projects { get; set; }
    }
}
