//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Material_InterplantRackTypes
    {
        public int ID { get; set; }
        public int ID_Material { get; set; }
        public int ID_RackType { get; set; }
    
        public virtual CTZ_Packaging_RackType CTZ_Packaging_RackType { get; set; }
        public virtual CTZ_Project_Materials CTZ_Project_Materials { get; set; }
    }
}
