//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Packaging_RackType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTZ_Packaging_RackType()
        {
            this.CTZ_Material_RackTypes = new HashSet<CTZ_Material_RackTypes>();
            this.CTZ_Material_RackTypes_History = new HashSet<CTZ_Material_RackTypes_History>();
            this.CTZ_Material_InterplantRackTypes = new HashSet<CTZ_Material_InterplantRackTypes>();
            this.CTZ_Material_InterplantRackTypes_History = new HashSet<CTZ_Material_InterplantRackTypes_History>();
            this.CTZ_Project_Materials = new HashSet<CTZ_Project_Materials>();
            this.CTZ_Project_Materials_History = new HashSet<CTZ_Project_Materials_History>();
        }
    
        public int ID_RackType { get; set; }
        public string RackTypeName { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Material_RackTypes> CTZ_Material_RackTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Material_RackTypes_History> CTZ_Material_RackTypes_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Material_InterplantRackTypes> CTZ_Material_InterplantRackTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Material_InterplantRackTypes_History> CTZ_Material_InterplantRackTypes_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Project_Materials> CTZ_Project_Materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Project_Materials_History> CTZ_Project_Materials_History { get; set; }
    }
}
