//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Slitting_Validation_Rules
    {
        public int ID_Rule { get; set; }
        public int ID_Production_Line { get; set; }
        public int Mults_Min { get; set; }
        public int Mults_Max { get; set; }
        public Nullable<double> Thickness_Min { get; set; }
        public Nullable<double> Thickness_Max { get; set; }
        public Nullable<double> Width_Min { get; set; }
        public Nullable<double> Width_Max { get; set; }
        public Nullable<double> Pitch_Min { get; set; }
        public Nullable<double> Pitch_Max { get; set; }
        public Nullable<double> Tensile_Min { get; set; }
        public Nullable<double> Tensile_Max { get; set; }
        public bool Is_Active { get; set; }
    
        public virtual CTZ_Production_Lines CTZ_Production_Lines { get; set; }
    }
}
