//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Line_Stroke_Settings
    {
        public int ID_Stroke_setting { get; set; }
        public int ID_Machine_Manufacturer { get; set; }
        public double Rotation_degrees { get; set; }
        public double Advance_mm { get; set; }
        public double Strokes { get; set; }
    
        public virtual CTZ_Line_Manufacturer CTZ_Line_Manufacturer { get; set; }
    }
}
