//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Material_InterplantAdditionals_History
    {
        public int ID { get; set; }
        public int ID_Material_History { get; set; }
        public int ID_Additional { get; set; }
    
        public virtual CTZ_Project_Materials_History CTZ_Project_Materials_History { get; set; }
    }
}
