//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Engineering_Dimension
    {
        public int ID_Engineering_Dimesion { get; set; }
        public Nullable<int> ID_Line { get; set; }
        public string Criteria { get; set; }
        public Nullable<double> Min_Value { get; set; }
        public Nullable<double> Max_Value { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual CTZ_Production_Lines CTZ_Production_Lines { get; set; }
    }
}
