//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Project_Assignment
    {
        public int ID_Assignment { get; set; }
        public int ID_Project { get; set; }
        public int ID_Department { get; set; }
        public int ID_Employee { get; set; }
        public int ID_Plant { get; set; }
        public int ID_Assignment_Status { get; set; }
        public System.DateTime Assignment_Date { get; set; }
        public Nullable<System.DateTime> Completition_Date { get; set; }
        public string Comments { get; set; }
    
        public virtual CTZ_Assignment_Status CTZ_Assignment_Status { get; set; }
        public virtual CTZ_Departments CTZ_Departments { get; set; }
        public virtual CTZ_plants CTZ_plants { get; set; }
        public virtual empleados empleados { get; set; }
        public virtual CTZ_Projects CTZ_Projects { get; set; }
    }
}
