//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Technical_Information_Line
    {
        public int ID_Technical_Information { get; set; }
        public int ID_Line { get; set; }
        public int ID_Material_type { get; set; }
        public int ID_Criteria { get; set; }
        public string TextValue { get; set; }
        public Nullable<double> NumericValue { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public bool IsActive { get; set; }
        public Nullable<double> AbsoluteTolerance { get; set; }
    
        public virtual CTZ_Material_Type CTZ_Material_Type { get; set; }
        public virtual CTZ_Production_Lines CTZ_Production_Lines { get; set; }
        public virtual CTZ_Technical_Criteria CTZ_Technical_Criteria { get; set; }
    }
}
