//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Temp_IHS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTZ_Temp_IHS()
        {
            this.CTZ_Temp_IHS_Production = new HashSet<CTZ_Temp_IHS_Production>();
        }
    
        public int ID_IHS { get; set; }
        public string Vehicle { get; set; }
        public string Program { get; set; }
        public Nullable<System.DateTime> SOP { get; set; }
        public Nullable<System.DateTime> EOP { get; set; }
        public Nullable<double> Max_Production { get; set; }
        public string Mnemonic_Vehicle_plant { get; set; }
        public string Production_Plant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Temp_IHS_Production> CTZ_Temp_IHS_Production { get; set; }
    }
}
