//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Departments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTZ_Departments()
        {
            this.CTZ_Employee_Departments = new HashSet<CTZ_Employee_Departments>();
            this.CTZ_Project_Assignment = new HashSet<CTZ_Project_Assignment>();
            this.CTZ_RejectionReason_Department = new HashSet<CTZ_RejectionReason_Department>();
            this.CTZ_RejectionReason = new HashSet<CTZ_RejectionReason>();
            this.CTZ_Department_Activity = new HashSet<CTZ_Department_Activity>();
        }
    
        public int ID_Department { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Employee_Departments> CTZ_Employee_Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Project_Assignment> CTZ_Project_Assignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_RejectionReason_Department> CTZ_RejectionReason_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_RejectionReason> CTZ_RejectionReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Department_Activity> CTZ_Department_Activity { get; set; }
    }
}
