//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Employee_Plants
    {
        public int ID_Employee_Plants { get; set; }
        public int ID_Employee { get; set; }
        public int ID_plant { get; set; }
    
        public virtual CTZ_plants CTZ_plants { get; set; }
        public virtual empleados empleados { get; set; }
    }
}
