//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Packaging_Additionals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTZ_Packaging_Additionals()
        {
            this.CTZ_Material_Additionals = new HashSet<CTZ_Material_Additionals>();
            this.CTZ_Material_Additionals_History = new HashSet<CTZ_Material_Additionals_History>();
            this.CTZ_Project_Materials = new HashSet<CTZ_Project_Materials>();
            this.CTZ_Project_Materials_History = new HashSet<CTZ_Project_Materials_History>();
        }
    
        public int ID_Additional { get; set; }
        public string AdditionalName { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Material_Additionals> CTZ_Material_Additionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Material_Additionals_History> CTZ_Material_Additionals_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Project_Materials> CTZ_Project_Materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Project_Materials_History> CTZ_Project_Materials_History { get; set; }
    }
}
