//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Project_Materials_History
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTZ_Project_Materials_History()
        {
            this.CTZ_Material_Additionals_History = new HashSet<CTZ_Material_Additionals_History>();
            this.CTZ_Material_Labels_History = new HashSet<CTZ_Material_Labels_History>();
            this.CTZ_Material_RackTypes_History = new HashSet<CTZ_Material_RackTypes_History>();
            this.CTZ_Material_StrapTypes_History = new HashSet<CTZ_Material_StrapTypes_History>();
        }
    
        public int ID_History { get; set; }
        public int ID_Version { get; set; }
        public Nullable<int> ID_IHS_Item { get; set; }
        public Nullable<int> Max_Production_SP { get; set; }
        public string Program_SP { get; set; }
        public string Vehicle_version { get; set; }
        public Nullable<System.DateTime> SOP_SP { get; set; }
        public Nullable<System.DateTime> EOP_SP { get; set; }
        public Nullable<System.DateTime> Real_SOP { get; set; }
        public Nullable<System.DateTime> Real_EOP { get; set; }
        public string Ship_To { get; set; }
        public string Part_Name { get; set; }
        public string Part_Number { get; set; }
        public Nullable<int> ID_Route { get; set; }
        public string Quality { get; set; }
        public Nullable<double> Tensile_Strenght { get; set; }
        public Nullable<int> ID_Material_type { get; set; }
        public Nullable<double> Thickness { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Pitch { get; set; }
        public Nullable<double> Theoretical_Gross_Weight { get; set; }
        public Nullable<double> Gross_Weight { get; set; }
        public Nullable<int> Annual_Volume { get; set; }
        public Nullable<double> Volume_Per_year { get; set; }
        public Nullable<int> ID_Shape { get; set; }
        public Nullable<double> Angle_A { get; set; }
        public Nullable<double> Angle_B { get; set; }
        public Nullable<double> Blanks_Per_Stroke { get; set; }
        public Nullable<double> Parts_Per_Vehicle { get; set; }
        public Nullable<int> ID_Theoretical_Blanking_Line { get; set; }
        public Nullable<int> ID_Real_Blanking_Line { get; set; }
        public Nullable<double> Theoretical_Strokes { get; set; }
        public Nullable<double> Real_Strokes { get; set; }
        public Nullable<double> Ideal_Cycle_Time_Per_Tool { get; set; }
        public Nullable<double> OEE { get; set; }
        public int ID_Project { get; set; }
        public string Vehicle { get; set; }
        public string Vehicle_2 { get; set; }
        public string Vehicle_3 { get; set; }
        public string Vehicle_4 { get; set; }
        public Nullable<double> ThicknessToleranceNegative { get; set; }
        public Nullable<double> ThicknessTolerancePositive { get; set; }
        public Nullable<double> WidthToleranceNegative { get; set; }
        public Nullable<double> WidthTolerancePositive { get; set; }
        public Nullable<double> PitchToleranceNegative { get; set; }
        public Nullable<double> PitchTolerancePositive { get; set; }
        public Nullable<double> WeightOfFinalMults { get; set; }
        public Nullable<double> Multipliers { get; set; }
        public Nullable<double> AngleAToleranceNegative { get; set; }
        public Nullable<double> AngleATolerancePositive { get; set; }
        public Nullable<double> AngleBToleranceNegative { get; set; }
        public Nullable<double> AngleBTolerancePositive { get; set; }
        public Nullable<double> MajorBase { get; set; }
        public Nullable<double> MajorBaseToleranceNegative { get; set; }
        public Nullable<double> MajorBaseTolerancePositive { get; set; }
        public Nullable<double> MinorBase { get; set; }
        public Nullable<double> MinorBaseToleranceNegative { get; set; }
        public Nullable<double> MinorBaseTolerancePositive { get; set; }
        public Nullable<double> Flatness { get; set; }
        public Nullable<double> FlatnessToleranceNegative { get; set; }
        public Nullable<double> FlatnessTolerancePositive { get; set; }
        public Nullable<double> MasterCoilWeight { get; set; }
        public Nullable<double> InnerCoilDiameterArrival { get; set; }
        public Nullable<double> OuterCoilDiameterArrival { get; set; }
        public Nullable<double> InnerCoilDiameterDelivery { get; set; }
        public Nullable<double> OuterCoilDiameterDelivery { get; set; }
        public string PackagingStandard { get; set; }
        public string SpecialRequirement { get; set; }
        public string SpecialPackaging { get; set; }
        public Nullable<int> ID_File_CAD_Drawing { get; set; }
        public Nullable<bool> TurnOver { get; set; }
        public string DM_status { get; set; }
        public string DM_status_comment { get; set; }
        public string TurnOverSide { get; set; }
        public Nullable<int> ID_File_Packaging { get; set; }
        public string StrapTypeObservations { get; set; }
        public string AdditionalsOtherDescription { get; set; }
        public string LabelOtherDescription { get; set; }
    
        public virtual CTZ_Files CTZ_Files { get; set; }
        public virtual CTZ_Files CTZ_Files1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Material_Additionals_History> CTZ_Material_Additionals_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Material_Labels_History> CTZ_Material_Labels_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Material_RackTypes_History> CTZ_Material_RackTypes_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Material_StrapTypes_History> CTZ_Material_StrapTypes_History { get; set; }
        public virtual CTZ_Material_Type CTZ_Material_Type { get; set; }
        public virtual CTZ_Production_Lines CTZ_Production_Lines { get; set; }
        public virtual CTZ_Production_Lines CTZ_Production_Lines1 { get; set; }
        public virtual CTZ_Route CTZ_Route { get; set; }
        public virtual SCDM_cat_forma_material SCDM_cat_forma_material { get; set; }
        public virtual CTZ_Projects CTZ_Projects { get; set; }
    }
}
