//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_Project_Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTZ_Project_Materials()
        {
            this.CTZ_Material_Additionals = new HashSet<CTZ_Material_Additionals>();
            this.CTZ_Material_Labels = new HashSet<CTZ_Material_Labels>();
            this.CTZ_Material_RackTypes = new HashSet<CTZ_Material_RackTypes>();
            this.CTZ_Material_StrapTypes = new HashSet<CTZ_Material_StrapTypes>();
        }
    
        public int ID_Material { get; set; }
        public Nullable<int> ID_IHS_Item { get; set; }
        public Nullable<int> Max_Production_SP { get; set; }
        public string Program_SP { get; set; }
        public string Vehicle_version { get; set; }
        public Nullable<System.DateTime> SOP_SP { get; set; }
        public Nullable<System.DateTime> EOP_SP { get; set; }
        public Nullable<System.DateTime> Real_SOP { get; set; }
        public Nullable<System.DateTime> Real_EOP { get; set; }
        public string Ship_To { get; set; }
        public string Part_Name { get; set; }
        public string Part_Number { get; set; }
        public Nullable<int> ID_Route { get; set; }
        public string Quality { get; set; }
        public Nullable<double> Tensile_Strenght { get; set; }
        public Nullable<int> ID_Material_type { get; set; }
        public Nullable<double> Thickness { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Pitch { get; set; }
        public Nullable<double> Theoretical_Gross_Weight { get; set; }
        public Nullable<double> Gross_Weight { get; set; }
        public Nullable<int> Annual_Volume { get; set; }
        public Nullable<double> Volume_Per_year { get; set; }
        public Nullable<int> ID_Shape { get; set; }
        public Nullable<double> Angle_A { get; set; }
        public Nullable<double> Angle_B { get; set; }
        public Nullable<double> Blanks_Per_Stroke { get; set; }
        public Nullable<double> Parts_Per_Vehicle { get; set; }
        public Nullable<int> ID_Theoretical_Blanking_Line { get; set; }
        public Nullable<int> ID_Real_Blanking_Line { get; set; }
        public Nullable<double> Theoretical_Strokes { get; set; }
        public Nullable<double> Real_Strokes { get; set; }
        public Nullable<double> Ideal_Cycle_Time_Per_Tool { get; set; }
        public Nullable<double> OEE { get; set; }
        public int ID_Project { get; set; }
        public string Vehicle { get; set; }
        public string Vehicle_2 { get; set; }
        public string Vehicle_3 { get; set; }
        public string Vehicle_4 { get; set; }
        public Nullable<double> ThicknessToleranceNegative { get; set; }
        public Nullable<double> ThicknessTolerancePositive { get; set; }
        public Nullable<double> WidthToleranceNegative { get; set; }
        public Nullable<double> WidthTolerancePositive { get; set; }
        public Nullable<double> PitchToleranceNegative { get; set; }
        public Nullable<double> PitchTolerancePositive { get; set; }
        public Nullable<double> WeightOfFinalMults { get; set; }
        public Nullable<double> Multipliers { get; set; }
        public Nullable<double> AngleAToleranceNegative { get; set; }
        public Nullable<double> AngleATolerancePositive { get; set; }
        public Nullable<double> AngleBToleranceNegative { get; set; }
        public Nullable<double> AngleBTolerancePositive { get; set; }
        public Nullable<double> MajorBase { get; set; }
        public Nullable<double> MajorBaseToleranceNegative { get; set; }
        public Nullable<double> MajorBaseTolerancePositive { get; set; }
        public Nullable<double> MinorBase { get; set; }
        public Nullable<double> MinorBaseToleranceNegative { get; set; }
        public Nullable<double> MinorBaseTolerancePositive { get; set; }
        public Nullable<double> Flatness { get; set; }
        public Nullable<double> FlatnessToleranceNegative { get; set; }
        public Nullable<double> FlatnessTolerancePositive { get; set; }
        public Nullable<double> MasterCoilWeight { get; set; }
        public Nullable<double> InnerCoilDiameterArrival { get; set; }
        public Nullable<double> OuterCoilDiameterArrival { get; set; }
        public Nullable<double> InnerCoilDiameterDelivery { get; set; }
        public Nullable<double> OuterCoilDiameterDelivery { get; set; }
        public string PackagingStandard { get; set; }
        public string SpecialRequirement { get; set; }
        public string SpecialPackaging { get; set; }
        public Nullable<int> ID_File_CAD_Drawing { get; set; }
        public Nullable<bool> TurnOver { get; set; }
        public string DM_status { get; set; }
        public string DM_status_comment { get; set; }
        public string TurnOverSide { get; set; }
        public Nullable<int> ID_File_Packaging { get; set; }
        public string StrapTypeObservations { get; set; }
        public string AdditionalsOtherDescription { get; set; }
        public string LabelOtherDescription { get; set; }
        public Nullable<double> TonsPerShift { get; set; }
        public Nullable<int> ID_Slitting_Line { get; set; }
        public Nullable<double> Width_Mults { get; set; }
        public Nullable<double> Width_Mults_Tol_Pos { get; set; }
        public Nullable<double> Width_Mults_Tol_Neg { get; set; }
        public Nullable<double> Width_Plates { get; set; }
        public Nullable<double> Width_Plates_Tol_Pos { get; set; }
        public Nullable<double> Width_Plates_Tol_Neg { get; set; }
        public Nullable<int> ID_Coil_Position { get; set; }
        public Nullable<int> ID_Arrival_Transport_Type { get; set; }
        public Nullable<int> ID_Arrival_Packaging_Type { get; set; }
        public Nullable<int> ID_Arrival_Protective_Material { get; set; }
        public string Arrival_Protective_Material_Other { get; set; }
        public Nullable<bool> Is_By_Container { get; set; }
        public Nullable<bool> Is_Stackable { get; set; }
        public Nullable<int> Stackable_Levels { get; set; }
        public string Arrival_Comments { get; set; }
        public string Arrival_Transport_Type_Other { get; set; }
        public Nullable<double> AnnualTonnage { get; set; }
        public Nullable<int> PiecesPerPackage { get; set; }
        public Nullable<int> StacksPerPackage { get; set; }
        public Nullable<double> PackageWeight { get; set; }
        public string DeliveryConditions { get; set; }
        public Nullable<bool> IsReturnableRack { get; set; }
        public Nullable<int> ReturnableUses { get; set; }
        public Nullable<bool> ScrapReconciliation { get; set; }
        public Nullable<double> ScrapReconciliationPercent { get; set; }
        public Nullable<bool> HeadTailReconciliation { get; set; }
        public Nullable<double> HeadTailReconciliationPercent { get; set; }
        public Nullable<int> ID_Delivery_Coil_Position { get; set; }
        public Nullable<int> ID_Delivery_Transport_Type { get; set; }
        public string Delivery_Transport_Type_Other { get; set; }
        public Nullable<int> ID_FreightType { get; set; }
        public Nullable<int> ID_Arrival_Warehouse { get; set; }
        public Nullable<double> ClientNetWeight { get; set; }
        public Nullable<bool> IsRunningChange { get; set; }
        public Nullable<int> ID_File_TechnicalSheet { get; set; }
        public Nullable<int> ID_File_Additional { get; set; }
        public Nullable<int> ID_File_ArrivalAdditional { get; set; }
        public Nullable<int> ID_File_CoilDataAdditional { get; set; }
        public Nullable<int> ID_File_SlitterDataAdditional { get; set; }
        public Nullable<int> ID_File_VolumeAdditional { get; set; }
        public Nullable<int> ID_File_OutboundFreightAdditional { get; set; }
        public Nullable<int> ID_File_DeliveryPackagingAdditional { get; set; }
    
        public virtual CTZ_Arrival_Warehouses CTZ_Arrival_Warehouses { get; set; }
        public virtual CTZ_Coil_Position CTZ_Coil_Position { get; set; }
        public virtual CTZ_Coil_Position CTZ_Coil_Position1 { get; set; }
        public virtual CTZ_Files CTZ_Files { get; set; }
        public virtual CTZ_Files CTZ_Files1 { get; set; }
        public virtual CTZ_Files CTZ_Files2 { get; set; }
        public virtual CTZ_Files CTZ_Files3 { get; set; }
        public virtual CTZ_Files CTZ_Files4 { get; set; }
        public virtual CTZ_Files CTZ_Files5 { get; set; }
        public virtual CTZ_Files CTZ_Files6 { get; set; }
        public virtual CTZ_Files CTZ_Files7 { get; set; }
        public virtual CTZ_Files CTZ_Files8 { get; set; }
        public virtual CTZ_Files CTZ_Files9 { get; set; }
        public virtual CTZ_FreightTypes CTZ_FreightTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Material_Additionals> CTZ_Material_Additionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Material_Labels> CTZ_Material_Labels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Material_RackTypes> CTZ_Material_RackTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Material_StrapTypes> CTZ_Material_StrapTypes { get; set; }
        public virtual CTZ_Material_Type CTZ_Material_Type { get; set; }
        public virtual CTZ_Packaging_Additionals CTZ_Packaging_Additionals { get; set; }
        public virtual CTZ_Packaging_RackType CTZ_Packaging_RackType { get; set; }
        public virtual CTZ_Production_Lines CTZ_Production_Lines { get; set; }
        public virtual CTZ_Production_Lines CTZ_Production_Lines1 { get; set; }
        public virtual CTZ_Production_Lines CTZ_Production_Lines2 { get; set; }
        public virtual CTZ_Projects CTZ_Projects { get; set; }
        public virtual CTZ_Route CTZ_Route { get; set; }
        public virtual CTZ_Transport_Types CTZ_Transport_Types { get; set; }
        public virtual CTZ_Transport_Types CTZ_Transport_Types1 { get; set; }
        public virtual SCDM_cat_forma_material SCDM_cat_forma_material { get; set; }
    }
}
