//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTZ_ExternalProcessorNames
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTZ_ExternalProcessorNames()
        {
            this.CTZ_Projects = new HashSet<CTZ_Projects>();
        }
    
        public int ID_ExternalProcessorName { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_ExternalProcessor { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CTZ_ExternalProcessors CTZ_ExternalProcessors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTZ_Projects> CTZ_Projects { get; set; }
    }
}
