//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GV_comprobacion
    {
        public int id_gv_solicitud { get; set; }
        public string business_card { get; set; }
        public Nullable<System.DateTime> fecha_comprobacion { get; set; }
        public int id_jefe_directo { get; set; }
        public Nullable<int> id_controlling { get; set; }
        public Nullable<int> id_contabilidad { get; set; }
        public Nullable<int> id_nomina { get; set; }
        public Nullable<System.DateTime> fecha_aceptacion_jefe_area { get; set; }
        public Nullable<System.DateTime> fecha_aceptacion_controlling { get; set; }
        public Nullable<System.DateTime> fecha_aceptacion_contabilidad { get; set; }
        public Nullable<System.DateTime> fecha_aceptacion_nomina { get; set; }
        public string comentario_rechazo { get; set; }
        public string comentario_adicional { get; set; }
        public bool american_express { get; set; }
        public Nullable<int> id_extracto_cuenta { get; set; }
        public string estatus { get; set; }
    
        public virtual biblioteca_digital biblioteca_digital { get; set; }
        public virtual empleados empleados { get; set; }
        public virtual empleados empleados1 { get; set; }
        public virtual empleados empleados2 { get; set; }
        public virtual empleados empleados3 { get; set; }
        public virtual GV_solicitud GV_solicitud { get; set; }
    }
}
