//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GV_comprobacion_rel_gastos
    {
        public int id { get; set; }
        public int id_gv_solicitud { get; set; }
        public Nullable<int> id_centro_costo { get; set; }
        public string concepto_tipo { get; set; }
        public Nullable<int> id_comprobacion_tipo_gastos_viaje { get; set; }
        public Nullable<int> id_comprobacion_tipo_pago { get; set; }
        public Nullable<int> num_concepto { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public string uuid { get; set; }
        public Nullable<double> tipo_cambio { get; set; }
        public string currency_iso { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<double> iva_porcentaje { get; set; }
        public Nullable<double> iva_total { get; set; }
        public Nullable<double> isr_porcentaje { get; set; }
        public Nullable<double> isr_total { get; set; }
        public Nullable<double> ieps_porcentaje { get; set; }
        public Nullable<double> ieps_total { get; set; }
        public Nullable<decimal> total_translados { get; set; }
        public Nullable<decimal> total_retenciones { get; set; }
        public Nullable<decimal> impuestos_locales { get; set; }
        public Nullable<decimal> total_mxn { get; set; }
        public string comentario { get; set; }
        public string factura { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual GV_centros_costo GV_centros_costo { get; set; }
        public virtual GV_comprobacion_tipo_gastos_viaje GV_comprobacion_tipo_gastos_viaje { get; set; }
        public virtual GV_comprobacion_tipo_pago GV_comprobacion_tipo_pago { get; set; }
        public virtual GV_solicitud GV_solicitud { get; set; }
    }
}
