//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GV_comprobacion_rel_gastos
    {
        public int id { get; set; }
        public int id_gv_solicitud { get; set; }
        public int id_comprobacion_tipo_gastos_viaje { get; set; }
        public string factura { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public string uuid { get; set; }
        public string currency_iso { get; set; }
        public decimal importe_factura { get; set; }
        public Nullable<double> tipo_cambio { get; set; }
        public string validacion { get; set; }
        public Nullable<double> iva { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual GV_comprobacion_tipo_gastos_viaje GV_comprobacion_tipo_gastos_viaje { get; set; }
        public virtual GV_solicitud GV_solicitud { get; set; }
    }
}
