//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GV_rel_gastos_solicitud
    {
        public int id { get; set; }
        public int id_gv_solicitud { get; set; }
        public int id_tipo_gastos_viaje { get; set; }
        public decimal importe { get; set; }
        public string currency_iso { get; set; }
        public decimal cantidad { get; set; }
        public string comentarios { get; set; }
    
        public virtual currency currency { get; set; }
        public virtual GV_solicitud GV_solicitud { get; set; }
        public virtual GV_tipo_gastos_viaje GV_tipo_gastos_viaje { get; set; }
    }
}
