//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IM_rel_archivos
    {
        public int id { get; set; }
        public int id_idea_mejora { get; set; }
        public int id_archivo { get; set; }
    
        public virtual biblioteca_digital biblioteca_digital { get; set; }
        public virtual IM_Idea_mejora IM_Idea_mejora { get; set; }
    }
}
