//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inspeccion_fallas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inspeccion_fallas()
        {
            this.inspeccion_pieza_descarte_produccion = new HashSet<inspeccion_pieza_descarte_produccion>();
        }
    
        public int id { get; set; }
        public int id_categoria_falla { get; set; }
        public string descripcion { get; set; }
        public bool aplica_en_calculo { get; set; }
        public bool dano_interno { get; set; }
        public bool dano_externo { get; set; }
        public bool activo { get; set; }
    
        public virtual inspeccion_categoria_fallas inspeccion_categoria_fallas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inspeccion_pieza_descarte_produccion> inspeccion_pieza_descarte_produccion { get; set; }
    }
}
