//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inspeccion_pieza_descarte_produccion
    {
        public int id { get; set; }
        public int id_produccion_registro { get; set; }
        public int id_falla { get; set; }
        public int cantidad { get; set; }
    
        public virtual inspeccion_fallas inspeccion_fallas { get; set; }
        public virtual produccion_registros produccion_registros { get; set; }
    }
}
