//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inspeccion_pieza_descarte_produccion
    {
        public int id { get; set; }
        public int id_produccion_registro { get; set; }
        public int id_falla { get; set; }
        public int cantidad { get; set; }
    
        public virtual inspeccion_fallas inspeccion_fallas { get; set; }
        public virtual produccion_registros produccion_registros { get; set; }
    }
}
