//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_GrupoLoteDetalle
    {
        public int DetalleID { get; set; }
        public int GrupoID { get; set; }
        public int LoteID { get; set; }
    
        public virtual Inv_LoteGrupo Inv_LoteGrupo { get; set; }
        public virtual Inv_Lote Inv_Lote { get; set; }
    }
}
