//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_asignacion_software
    {
        public int id { get; set; }
        public int id_inventory_software { get; set; }
        public int id_sistemas { get; set; }
        public int id_empleado { get; set; }
        public string usuario { get; set; }
    
        public virtual IT_inventory_software IT_inventory_software { get; set; }
        public virtual empleados empleados { get; set; }
        public virtual empleados empleados1 { get; set; }
    }
}
