//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_asignacion_hardware
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IT_asignacion_hardware()
        {
            this.IT_asignacion_hardware_rel_items = new HashSet<IT_asignacion_hardware_rel_items>();
            this.IT_matriz_hardware = new HashSet<IT_matriz_hardware>();
        }
    
        public int id { get; set; }
        public int id_iatf_version { get; set; }
        public int id_empleado { get; set; }
        public int id_sistemas { get; set; }
        public Nullable<int> id_biblioteca_digital { get; set; }
        public System.DateTime fecha_asignacion { get; set; }
        public Nullable<System.DateTime> fecha_desasignacion { get; set; }
        public bool es_asignacion_actual { get; set; }
        public Nullable<int> id_responsable_principal { get; set; }
        public Nullable<int> id_cellular_line { get; set; }
        public bool es_asignacion_linea_actual { get; set; }
        public string comentario_desasignacion { get; set; }
    
        public virtual biblioteca_digital biblioteca_digital { get; set; }
        public virtual empleados empleados { get; set; }
        public virtual empleados empleados1 { get; set; }
        public virtual empleados empleados2 { get; set; }
        public virtual IATF_revisiones IATF_revisiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_asignacion_hardware_rel_items> IT_asignacion_hardware_rel_items { get; set; }
        public virtual IT_inventory_cellular_line IT_inventory_cellular_line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_matriz_hardware> IT_matriz_hardware { get; set; }
    }
}
