//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_asignacion_hardware_rel_items
    {
        public int id { get; set; }
        public int id_asignacion_hardware { get; set; }
        public Nullable<int> id_it_inventory_item { get; set; }
        public Nullable<int> id_it_inventory_generico { get; set; }
        public string comments { get; set; }
    
        public virtual IT_inventory_items_genericos IT_inventory_items_genericos { get; set; }
        public virtual IT_inventory_items IT_inventory_items { get; set; }
        public virtual IT_asignacion_hardware IT_asignacion_hardware { get; set; }
    }
}
