//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_equipos_rel_checklist_actividades
    {
        public int id { get; set; }
        public int id_equipo_checklist { get; set; }
        public int id_it_equipo_actividad { get; set; }
        public string observacion { get; set; }
        public string estatus { get; set; }
    
        public virtual IT_equipos_checklist IT_equipos_checklist { get; set; }
        public virtual IT_equipos_checklist_actividades IT_equipos_checklist_actividades { get; set; }
    }
}
