//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_ExportUsers
    {
        public int id { get; set; }
        public string C8ID { get; set; }
        public string userPrincipalName { get; set; }
        public string displayName { get; set; }
        public string surname { get; set; }
        public string mail { get; set; }
        public string givenName { get; set; }
        public string C_id { get; set; }
        public string userType { get; set; }
        public string jobTitle { get; set; }
        public string department { get; set; }
        public string accountEnabled { get; set; }
        public string usageLocation { get; set; }
        public string streetAddress { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string officeLocation { get; set; }
        public string city { get; set; }
        public string postalCode { get; set; }
        public string telephoneNumber { get; set; }
        public string mobilePhone { get; set; }
        public string alternateEmailAddress { get; set; }
        public string ageGroup { get; set; }
        public string consentProvidedForMinor { get; set; }
        public string legalAgeGroupClassification { get; set; }
        public string companyName { get; set; }
        public string creationType { get; set; }
        public string directorySynced { get; set; }
        public string invitationState { get; set; }
        public string identityIssuer { get; set; }
        public string createdDateTime { get; set; }
        public System.DateTime updateTime { get; set; }
    }
}
