//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_Export4Import
    {
        public int id { get; set; }
        public string C8ID { get; set; }
        public string tksir { get; set; }
        public string tktitle { get; set; }
        public string tknameprefix { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string tkbirth { get; set; }
        public string tksex { get; set; }
        public string tkstreet { get; set; }
        public string tkpostalcode { get; set; }
        public string tkpostaladdress { get; set; }
        public string tkaddaddon { get; set; }
        public string tkfedst { get; set; }
        public string tkcountry { get; set; }
        public string tkcountrykey { get; set; }
        public string tknationality { get; set; }
        public string tkpreflang { get; set; }
        public string tkempno { get; set; }
        public string tkfkz6 { get; set; }
        public string tkfkzext { get; set; }
        public string tkuniqueid { get; set; }
        public string tkpstatus { get; set; }
        public string tkcostcenter { get; set; }
        public string tkdepartment { get; set; }
        public string tkfunction { get; set; }
        public string tkorgstreet { get; set; }
        public string tkorgpostalcode { get; set; }
        public string tkorgpostaladdress { get; set; }
        public string tkorgaddonaddr { get; set; }
        public string tkorgfedst { get; set; }
        public string tkorgcountry { get; set; }
        public string tkorgcountrykey { get; set; }
        public string tkapsite { get; set; }
        public string tkorgkey { get; set; }
        public string tkbuilding { get; set; }
        public string email { get; set; }
        public string tkareacode { get; set; }
        public string tkphoneext { get; set; }
        public string tkorgfax { get; set; }
        public string tkmobile { get; set; }
        public string tkgodfather { get; set; }
        public string tkprefdelmethod { get; set; }
        public string tkedateorg { get; set; }
        public string tkedatetrust { get; set; }
        public string tkldateorg { get; set; }
        public string tklreason { get; set; }
        public string shares { get; set; }
        public string supervisoryboardelection { get; set; }
        public string tkbkz { get; set; }
        public string tkinside { get; set; }
        public System.DateTime updateTime { get; set; }
    }
}
