//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_inventory_cellular_line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IT_inventory_cellular_line()
        {
            this.IT_asignacion_cellular_line = new HashSet<IT_asignacion_cellular_line>();
        }
    
        public int id { get; set; }
        public int id_inventory_celullar_plan { get; set; }
        public int id_planta { get; set; }
        public string numero_celular { get; set; }
        public Nullable<System.DateTime> fecha_corte { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_asignacion_cellular_line> IT_asignacion_cellular_line { get; set; }
        public virtual IT_inventory_cellular_plans IT_inventory_cellular_plans { get; set; }
        public virtual plantas plantas { get; set; }
    }
}
