//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_inventory_cellular_plans
    {
        public int id { get; set; }
        public string nombre_plan { get; set; }
        public string nombre_compania { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string comentarios { get; set; }
        public bool activo { get; set; }
    }
}
