//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_mantenimientos_rel_checklist
    {
        public int id { get; set; }
        public int id_mantenimiento { get; set; }
        public int id_item_checklist_mantenimiento { get; set; }
        public Nullable<bool> terminado { get; set; }
        public string comentarios { get; set; }
    
        public virtual IT_mantenimientos IT_mantenimientos { get; set; }
        public virtual IT_mantenimientos_checklist_item IT_mantenimientos_checklist_item { get; set; }
    }
}
