//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IT_matriz_requerimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IT_matriz_requerimientos()
        {
            this.IT_matriz_carpetas = new HashSet<IT_matriz_carpetas>();
            this.IT_matriz_comunicaciones = new HashSet<IT_matriz_comunicaciones>();
            this.IT_matriz_hardware = new HashSet<IT_matriz_hardware>();
            this.IT_matriz_software = new HashSet<IT_matriz_software>();
        }

        [Display(Name = "Folio")]
        public int id { get; set; }

        [Display(Name = "Empleado")]
        public int id_empleado { get; set; }

        [Required]
        [Display(Name = "Jefe Directo")]
        public int id_jefe_directo { get; set; }
        [Required]
        [Display(Name = "Acceso a Internet")]
        public int id_internet_tipo { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Solicitud")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha_solicitud { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha Aprobación")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fecha_aprobacion_jefe { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Cierre")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fecha_cierre { get; set; }

        [Display(Name = "Estado")]
        public string estatus { get; set; }

        [StringLength(350, MinimumLength = 5)]
        [Display(Name = "Comentarios Adicionales")]
        public string comentario { get; set; }

        [StringLength(350, MinimumLength = 5)]
        [Display(Name = "Razón Rechazo")]
        public string comentario_rechazo { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual empleados empleados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_matriz_carpetas> IT_matriz_carpetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_matriz_comunicaciones> IT_matriz_comunicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_matriz_hardware> IT_matriz_hardware { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_matriz_software> IT_matriz_software { get; set; }
    }
}
