//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_matriz_comunicaciones
    {
        public int id { get; set; }
        public int id_matriz_requerimientos { get; set; }
        public int id_it_comunicaciones { get; set; }
        public string descripcion { get; set; }
        public string comentario { get; set; }
        public Nullable<bool> completado { get; set; }
    
        public virtual IT_comunicaciones_tipo IT_comunicaciones_tipo { get; set; }
        public virtual IT_matriz_requerimientos IT_matriz_requerimientos { get; set; }
    }
}
