//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_mantenimientos_aplazamientos
    {
        public int id { get; set; }
        public int id_mantenimiento { get; set; }
        public int id_sistemas { get; set; }
        public System.DateTime fecha_anterior { get; set; }
        public System.DateTime nueva_fecha { get; set; }
        public string motivo { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual IT_mantenimientos IT_mantenimientos { get; set; }
    }
}
