//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_notificaciones_actividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IT_notificaciones_actividad()
        {
            this.IT_notificaciones_usuarios = new HashSet<IT_notificaciones_usuarios>();
            this.IT_notificaciones_recordatorio = new HashSet<IT_notificaciones_recordatorio>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> periodo { get; set; }
        public string tipo_periodo { get; set; }
        public bool es_recurrente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_notificaciones_usuarios> IT_notificaciones_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_notificaciones_recordatorio> IT_notificaciones_recordatorio { get; set; }
    }
}
