//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_notificaciones_usuarios
    {
        public int id { get; set; }
        public int id_notificaciones_actividad { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public string correo { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual IT_notificaciones_actividad IT_notificaciones_actividad { get; set; }
    }
}
