//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_site_checklist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IT_site_checklist()
        {
            this.IT_site_checklist_rel_actividades = new HashSet<IT_site_checklist_rel_actividades>();
        }
    
        public int id { get; set; }
        public int id_site { get; set; }
        public int id_sistemas { get; set; }
        public string observacion_particular { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string estatus { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual IT_site IT_site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_site_checklist_rel_actividades> IT_site_checklist_rel_actividades { get; set; }
    }
}
