//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_UsuariosActivos
    {
        public int id { get; set; }
        public string Numero { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombre { get; set; }
        public string Antiguedad { get; set; }
        public string Puesto { get; set; }
        public string Departamento { get; set; }
        public string Planta { get; set; }
        public string Area { get; set; }
        public string DepartamentoNum { get; set; }
        public string Genero { get; set; }
        public string C8ID { get; set; }
        public System.DateTime updateTime { get; set; }
    }
}
