//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_inicio_sesion
    {
        public int id { get; set; }
        public string id_usuario { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
