//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public string Matnr { get; set; }
        public System.DateTime LastSyncTimestamp { get; set; }
        public string Mtart { get; set; }
        public string Bismt { get; set; }
        public Nullable<double> Brgew { get; set; }
        public Nullable<double> Ntgwe { get; set; }
        public string Meins { get; set; }
        public string Groes { get; set; }
        public string Vmsta { get; set; }
        public string Gewei { get; set; }
        public string ZZMATTYP { get; set; }
        public Nullable<bool> ZZCUSTSCRP { get; set; }
        public Nullable<bool> ZZENGSCRP { get; set; }
        public string ZZIHSNUM1 { get; set; }
        public string ZZIHSNUM2 { get; set; }
        public string ZZIHSNUM3 { get; set; }
        public string ZZIHSNUM4 { get; set; }
        public string ZZIHSNUM5 { get; set; }
        public Nullable<double> ZZPKGPCS { get; set; }
        public Nullable<double> ZZTHCKNSS { get; set; }
        public Nullable<double> ZZWIDTH { get; set; }
        public Nullable<double> ZZADVANCE { get; set; }
        public Nullable<double> ZZHTALSCRP { get; set; }
        public Nullable<double> ZZCARPCS { get; set; }
        public Nullable<double> ZZINITWT { get; set; }
        public Nullable<double> ZZMINWT { get; set; }
        public Nullable<double> ZZMAXWT { get; set; }
        public Nullable<double> ZZSTKPCS { get; set; }
        public Nullable<double> ZZANGLEA { get; set; }
        public Nullable<double> ZZANGLEB { get; set; }
        public Nullable<double> ZZREALNTWT { get; set; }
        public Nullable<double> ZZREALGRWT { get; set; }
        public Nullable<bool> ZZDOUPCS { get; set; }
        public string ZZCOILSLTPOS { get; set; }
        public Nullable<double> ZZMXWTTOLP { get; set; }
        public Nullable<double> ZZMXWTTOLN { get; set; }
        public Nullable<double> ZZMNWTTOLP { get; set; }
        public Nullable<double> ZZMNWTTOLN { get; set; }
        public Nullable<bool> ZZWH { get; set; }
        public string ZZTRANSP { get; set; }
        public string ZZTKMMSOP { get; set; }
        public string ZZTKMMEOP { get; set; }
        public Nullable<double> ZZPPACKAGE { get; set; }
        public Nullable<double> ZZSPACKAGE { get; set; }
        public Nullable<bool> ZZREAPPL { get; set; }
        public string ZZSTAMD { get; set; }
        public string ZZIDPNUM { get; set; }
        public string ZZIDTOOL { get; set; }
        public string ZZIDOBSOL { get; set; }
        public string ZZTOURD { get; set; }
        public string ZZTOLMAXWT { get; set; }
        public string ZZTOLMINWT { get; set; }
        public string ZZPALLET { get; set; }
        public string ZZMTLTYP { get; set; }
        public string ZZSELLTYP { get; set; }
        public string ZZBUSSMODL { get; set; }
    }
}
