//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Portal_2_0_ServicesEntities : DbContext
    {
        public Portal_2_0_ServicesEntities()
            : base("name=Portal_2_0_ServicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BatchCharacteristics> BatchCharacteristics { get; set; }
        public virtual DbSet<Batches> Batches { get; set; }
        public virtual DbSet<MaterialCharacteristics> MaterialCharacteristics { get; set; }
        public virtual DbSet<MaterialDescriptions> MaterialDescriptions { get; set; }
        public virtual DbSet<MaterialPlants> MaterialPlants { get; set; }
        public virtual DbSet<BomItems> BomItems { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<vw_ReporteBalanceMateriales> vw_ReporteBalanceMateriales { get; set; }
    
        public virtual ObjectResult<sp_GetReporteBalanceScrap_Result> sp_GetReporteBalanceScrap(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetReporteBalanceScrap_Result>("sp_GetReporteBalanceScrap", fechaInicioParameter, fechaFinParameter);
        }
    }
}
