//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_Cargas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OT_Cargas()
        {
            this.OT_Datos = new HashSet<OT_Datos>();
        }
    
        public int ID_CargaOT { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public string UsuarioCarga { get; set; }
        public string NombreArchivo { get; set; }
        public string Comentarios { get; set; }
        public int TotalRegistros { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OT_Datos> OT_Datos { get; set; }
    }
}
