//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_Datos
    {
        public long ID_DatoOT { get; set; }
        public int ID_CargaOT { get; set; }
        public Nullable<int> Posicion { get; set; }
        public string ClDocumentoCompras { get; set; }
        public string TipoDocCompras { get; set; }
        public string GrupoCompras { get; set; }
        public Nullable<System.DateTime> FechaDocumento { get; set; }
        public string Material { get; set; }
        public string TextoBreve { get; set; }
        public string IndicadorBorrado { get; set; }
        public string Centro { get; set; }
        public string Almacen { get; set; }
        public Nullable<decimal> CantidadPedido { get; set; }
        public string UnidadMedidaPedido { get; set; }
        public Nullable<decimal> CantidadUMA { get; set; }
        public string UnidadMedidaAlmacen { get; set; }
        public Nullable<decimal> PrecioNeto { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> CantidadBase { get; set; }
        public Nullable<decimal> CtdPrevPendiente { get; set; }
        public Nullable<decimal> PorEntregarCantidad { get; set; }
        public Nullable<decimal> PorEntregarValor { get; set; }
        public Nullable<decimal> PorCalcularCantidad { get; set; }
        public string TipoImputacion { get; set; }
        public Nullable<decimal> PorCalcularValor { get; set; }
        public string IndLiberacion { get; set; }
        public string DocumentoCompras { get; set; }
        public string ProveedorCentroSuministrador { get; set; }
    
        public virtual OT_Cargas OT_Cargas { get; set; }
    }
}
