//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLC_Historical_Values
    {
        public int ID_Historical_Value { get; set; }
        public int ID_Tag { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Valor { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
    
        public virtual PLC_Tags PLC_Tags { get; set; }
    }
}
