//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PM_autorizadores
    {
        public int id { get; set; }
        [Required(ErrorMessage = "El campo empleado es requerido.", AllowEmptyStrings = false)]
        [Display(Name = "Empleado")]
        public Nullable<int> id_empleado { get; set; }

        [Display(Name = "Estado")]
        public bool activo { get; set; }

        //Concatena clave y nombre
        public string ConcatNameAutorizador
        {
            get
            {
                return empleados.ConcatNombre;
            }
        }

        public virtual empleados empleados { get; set; }
    }
}
