//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class produccion_registros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produccion_registros()
        {
            this.produccion_lotes = new HashSet<produccion_lotes>();
        }
    
        public int id { get; set; }
        [Display(Name = "Planta")]
        public Nullable<int> clave_planta { get; set; }
        [Display(Name = "Línea")]
        public Nullable<int> id_linea { get; set; }

        [Required]
        [Display(Name = "Operador")]
        public Nullable<int> id_operador { get; set; }

        [Required]
        [Display(Name = "Supervisor")]
        public Nullable<int> id_supervisor { get; set; }
        [Display(Name = "Turno")]
        public Nullable<int> id_turno { get; set; }

        [Required]
        [Display(Name = "SAP Platina")]
        public string sap_platina { get; set; }

        [Required]
        [Display(Name = "SAP Rollo")]
        public string sap_rollo { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual plantas plantas { get; set; }
        public virtual produccion_datos_entrada produccion_datos_entrada { get; set; }
        public virtual produccion_lineas produccion_lineas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produccion_lotes> produccion_lotes { get; set; }
        public virtual produccion_operadores produccion_operadores { get; set; }
        public virtual produccion_supervisores produccion_supervisores { get; set; }
        public virtual produccion_turnos produccion_turnos { get; set; }
    }
}
