//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produccion_datos_entrada
    {
        public int id_produccion_registro { get; set; }
        public Nullable<double> peso_real_pieza_neto { get; set; }
        public string orden_sap { get; set; }
        public string orden_sap_2 { get; set; }
        public Nullable<int> piezas_por_golpe { get; set; }
        public string numero_rollo { get; set; }
        public string lote_rollo { get; set; }
        public Nullable<double> peso_etiqueta { get; set; }
        public Nullable<double> peso_regreso_rollo_real { get; set; }
        public Nullable<double> peso_bascula_kgs { get; set; }
        public Nullable<double> peso_despunte_kgs { get; set; }
        public Nullable<double> peso_cola_kgs { get; set; }
        public Nullable<int> total_piezas_ajuste { get; set; }
        public Nullable<int> ordenes_por_pieza { get; set; }
        public string comentarios { get; set; }
        public Nullable<double> peso_real_pieza_neto_platina_2 { get; set; }
        public Nullable<int> total_piezas_ajuste_platina_2 { get; set; }
    
        public virtual produccion_registros produccion_registros { get; set; }
    }
}
