//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produccion_respaldo : IEquatable<produccion_respaldo>
    {
        public int id { get; set; }
        public Nullable<int> empleado_id { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public string planta { get; set; }
        public string linea { get; set; }
        public string operador { get; set; }
        public string supervisor { get; set; }
        public string sap_platina { get; set; }
        public string tipo_material { get; set; }
        public string numero_parte_cliente { get; set; }
        public string sap_rollo { get; set; }
        public string material { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string turno { get; set; }
        public Nullable<System.DateTime> hora { get; set; }
        public string orden_sap { get; set; }
        public string orden_sap_2 { get; set; }
        public Nullable<double> pieza_por_golpe { get; set; }
        public string numero_rollo { get; set; }
        public string lote_rollo { get; set; }
        public Nullable<double> peso_etiqueta { get; set; }
        public Nullable<double> peso_regreso_rollo_real { get; set; }
        public Nullable<double> peso_rollo_usado { get; set; }
        public Nullable<double> peso_bascula_kgs { get; set; }
        public Nullable<double> piezas_por_paquete { get; set; }
        public Nullable<double> total_piezas { get; set; }
        public Nullable<double> peso_rollo_consumido { get; set; }
        public Nullable<double> numero_golpes { get; set; }
        public Nullable<double> peso_despunte_kgs { get; set; }
        public Nullable<double> peso_cola_kgs { get; set; }
        public Nullable<double> porcentaje_punta_y_colas { get; set; }
        public Nullable<double> total_piezas_ajuste { get; set; }
        public Nullable<double> peso_bruto_kgs { get; set; }
        public Nullable<double> peso_real_pieza_bruto { get; set; }
        public Nullable<double> peso_real_pieza_neto { get; set; }
        public Nullable<double> scrap_natural { get; set; }
        public Nullable<double> peso_neto_sap { get; set; }
        public Nullable<double> peso_bruto_sap { get; set; }
        public Nullable<double> balance_scrap { get; set; }
        public Nullable<double> ordenes_por_pieza { get; set; }
        public Nullable<double> peso_rollo_usado_real_kgs { get; set; }
        public Nullable<double> peso_bruto_total_piezas_kgs { get; set; }
        public Nullable<double> peso_neto_total_piezas_kgs { get; set; }
        public Nullable<double> scrap_ingenieria_buenas_mas_ajuste { get; set; }
        public Nullable<double> peso_neto_total_piezas_ajuste { get; set; }
        public Nullable<double> peso_punta_y_colas_reales { get; set; }
        public Nullable<double> balance_scrap_real { get; set; }
    
        public virtual empleados empleados { get; set; }

        //para realizar la comparacion   
        public bool Equals(produccion_respaldo other)
        {
            if (other is null)
                return false;

            return
                    this.linea == other.linea
                    && this.planta == other.planta
                    && this.hora == other.hora                   
                ;
        }

        public override bool Equals(object obj) => Equals(obj as class_v3);
        public override int GetHashCode() => (linea, planta, hora).GetHashCode();
    }
}
