//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro_eventos
    {
        public int IdEvento { get; set; }
        public string IdUsuario { get; set; }
        public System.DateTime FechaEvento { get; set; }
        public string TipoEvento { get; set; }
        public string Origen { get; set; }
        public string Descripcion { get; set; }
        public byte Gravedad { get; set; }
        public int NumeroError { get; set; }
    }
}
