//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RM_cambio_estatus
    {
        public int clave { get; set; }
        public System.DateTime capturaFecha { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public int remisionCabeceraClave { get; set; }
        public int catalogoEstatusClave { get; set; }
        public string nombre_usuario_old { get; set; }
        public string texto { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual RM_estatus RM_estatus { get; set; }
        public virtual RM_cabecera RM_cabecera { get; set; }
    }
}
