//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RM_elemento
    {
        public int clave { get; set; }
        public Nullable<bool> activo { get; set; }
        public int remisionCabeceraClave { get; set; }
        public System.DateTime capturaFecha { get; set; }
        public string numeroParteCliente { get; set; }
        public string numeroMaterial { get; set; }
        public string numeroLote { get; set; }
        public string numeroRollo { get; set; }
        public double cantidad { get; set; }
        public double peso { get; set; }
        public string remisionSap { get; set; }
    
        public virtual RM_cabecera RM_cabecera { get; set; }
    }
}
