//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCDM_solicitud_rel_cambio_budget
    {
        public int id { get; set; }
        public int id_solicitud { get; set; }
        public Nullable<int> id_planta { get; set; }
        public string material_existente { get; set; }
        public Nullable<double> peso_bruto_real_bascula { get; set; }
        public Nullable<double> peso_neto_real_bascula { get; set; }
        public Nullable<double> angulo_a { get; set; }
        public Nullable<double> angulo_b { get; set; }
        public Nullable<double> scrap_permitido_puntas_colas { get; set; }
        public string pieza_doble { get; set; }
        public Nullable<bool> reaplicacion { get; set; }
        public Nullable<bool> conciliacion_puntas_colas { get; set; }
        public Nullable<bool> conciliacion_scrap_ingenieria { get; set; }
        public string tipo_metal { get; set; }
        public string tipo_material { get; set; }
        public string tipo_venta { get; set; }
        public string modelo_negocio { get; set; }
        public string posicion_rollo { get; set; }
        public string IHS_num_1 { get; set; }
        public string IHS_num_2 { get; set; }
        public string IHS_num_3 { get; set; }
        public string IHS_num_4 { get; set; }
        public string IHS_num_5 { get; set; }
        public Nullable<double> piezas_por_auto { get; set; }
        public Nullable<double> piezas_por_golpe { get; set; }
        public Nullable<double> piezas_por_paquete { get; set; }
        public Nullable<double> peso_inicial { get; set; }
        public Nullable<double> peso_maximo { get; set; }
        public Nullable<double> peso_maximo_tolerancia_positiva { get; set; }
        public Nullable<double> peso_maximo_tolerancia_negativa { get; set; }
        public Nullable<double> peso_minimo { get; set; }
        public Nullable<double> peso_minimo_tolerancia_positiva { get; set; }
        public Nullable<double> peso_minimo_tolerancia_negativa { get; set; }
        public string comentarios { get; set; }
        public string ejecucion_correcta { get; set; }
        public string resultado { get; set; }
    
        public virtual plantas plantas { get; set; }
        public virtual SCDM_solicitud SCDM_solicitud { get; set; }
    }
}
