//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCDM_solicitud_rel_lista_tecnica
    {
        public int id_solicitud_rel_item_material { get; set; }
        public Nullable<int> id_componente { get; set; }
        public string resultado { get; set; }
        public Nullable<double> sobrante_mm { get; set; }
        public Nullable<int> cantidad_platinas { get; set; }
        public Nullable<int> cantidad_cintas { get; set; }
        public Nullable<System.DateTime> fecha_validez { get; set; }
    
        public virtual SCDM_solicitud_rel_item_material SCDM_solicitud_rel_item_material { get; set; }
        public virtual SCDM_solicitud_rel_item_material SCDM_solicitud_rel_item_material1 { get; set; }
    }
}
