//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCDM_solicitud_rel_creacion_referencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCDM_solicitud_rel_creacion_referencia()
        {
            this.SCDM_solicitud_rel_extension_almacenes = new HashSet<SCDM_solicitud_rel_extension_almacenes>();
            this.SCDM_solicitud_rel_extension = new HashSet<SCDM_solicitud_rel_extension>();
            this.SCDM_solicitud_rel_facturacion = new HashSet<SCDM_solicitud_rel_facturacion>();
        }
    
        public int id { get; set; }
        public int id_solicitud { get; set; }
        public Nullable<int> id_tipo_venta { get; set; }
        public Nullable<int> id_tipo_material { get; set; }
        public Nullable<int> id_planta { get; set; }
        public string motivo_creacion { get; set; }
        public string material_existente { get; set; }
        public string nuevo_dato { get; set; }
        public string comentarios { get; set; }
        public string resultado { get; set; }
        public string ejecucion_correcta { get; set; }
        public string nuevo_material { get; set; }
        public string numero_antiguo_material { get; set; }
        public Nullable<double> peso_bruto { get; set; }
        public string unidad_medida_inventario { get; set; }
        public string commodity { get; set; }
        public string grado_calidad { get; set; }
        public Nullable<double> espesor_mm { get; set; }
        public Nullable<double> espesor_tolerancia_negativa_mm { get; set; }
        public Nullable<double> espesor_tolerancia_positiva_mm { get; set; }
        public Nullable<double> ancho_mm { get; set; }
        public Nullable<double> ancho_tolerancia_negativa_mm { get; set; }
        public Nullable<double> ancho_tolerancia_positiva_mm { get; set; }
        public Nullable<double> avance_mm { get; set; }
        public Nullable<double> avance_tolerancia_negativa_mm { get; set; }
        public Nullable<double> avance_tolerancia_positiva_mm { get; set; }
        public Nullable<double> planicidad_mm { get; set; }
        public string superficie { get; set; }
        public string tratamiento_superficial { get; set; }
        public string peso_recubrimiento { get; set; }
        public string molino { get; set; }
        public string forma { get; set; }
        public string cliente { get; set; }
        public string numero_parte { get; set; }
        public string msa_honda { get; set; }
        public Nullable<double> diametro_interior { get; set; }
        public Nullable<double> diametro_exterior { get; set; }
        public Nullable<double> peso_neto { get; set; }
        public string resultado_update { get; set; }
        public string descripcion_es { get; set; }
        public string descripcion_en { get; set; }
        public string tipo_metal { get; set; }
        public string tipo_material_text { get; set; }
    
        public virtual plantas plantas { get; set; }
        public virtual SCDM_cat_tipo_materiales_solicitud SCDM_cat_tipo_materiales_solicitud { get; set; }
        public virtual SCDM_cat_tipo_venta SCDM_cat_tipo_venta { get; set; }
        public virtual SCDM_solicitud SCDM_solicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCDM_solicitud_rel_extension_almacenes> SCDM_solicitud_rel_extension_almacenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCDM_solicitud_rel_extension> SCDM_solicitud_rel_extension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCDM_solicitud_rel_facturacion> SCDM_solicitud_rel_facturacion { get; set; }
    }
}
