//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCDM_solicitud_rel_item_material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCDM_solicitud_rel_item_material()
        {
            this.SCDM_solicitud_rel_lista_tecnica = new HashSet<SCDM_solicitud_rel_lista_tecnica>();
            this.SCDM_solicitud_rel_orden_compra = new HashSet<SCDM_solicitud_rel_orden_compra>();
        }
    
        public int id { get; set; }
        public int id_solicitud { get; set; }
        public int id_tipo_material { get; set; }
        public Nullable<int> id_tipo_venta { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<int> id_molino { get; set; }
        public Nullable<int> id_metal { get; set; }
        public Nullable<int> id_unidad_medida_inventario { get; set; }
        public Nullable<int> id_tipo_recubrimiento { get; set; }
        public Nullable<int> id_clase_aprovisionamiento { get; set; }
        public Nullable<int> id_diametro_interior { get; set; }
        public Nullable<int> id_peso_recubrimiento { get; set; }
        public Nullable<int> id_parte_interior_exterior { get; set; }
        public Nullable<int> id_posicion_rollo { get; set; }
        public Nullable<int> id_ihs_1 { get; set; }
        public Nullable<int> id_ihs_2 { get; set; }
        public Nullable<int> id_ihs_3 { get; set; }
        public Nullable<int> id_ihs_4 { get; set; }
        public Nullable<int> id_ihs_5 { get; set; }
        public Nullable<int> id_modelo_negocio { get; set; }
        public Nullable<int> id_tipo_transito { get; set; }
        public Nullable<int> id_procesador_externo { get; set; }
        public Nullable<int> id_disponente { get; set; }
        public Nullable<bool> material_del_cliente { get; set; }
        public string numero_odc_cliente { get; set; }
        public Nullable<bool> requiere_ppaps { get; set; }
        public Nullable<bool> requiere_imds { get; set; }
        public string numero_material { get; set; }
        public string descripcion_material_es { get; set; }
        public string descripcion_material_en { get; set; }
        public string grado_calidad { get; set; }
        public string numero_parte { get; set; }
        public string descripcion_numero_parte { get; set; }
        public string norma_referencia { get; set; }
        public Nullable<double> espesor_mm { get; set; }
        public Nullable<double> espesor_tolerancia_negativa_mm { get; set; }
        public Nullable<double> espesor_tolerancia_positiva_mm { get; set; }
        public Nullable<double> ancho_mm { get; set; }
        public Nullable<double> ancho_tolerancia_negativa_mm { get; set; }
        public Nullable<double> ancho_tolerancia_positiva_mm { get; set; }
        public Nullable<double> diametro_exterior_maximo_mm { get; set; }
        public Nullable<double> peso_min_kg { get; set; }
        public Nullable<double> peso_max_kg { get; set; }
        public Nullable<bool> procesador_externo { get; set; }
        public string numero_antiguo_material { get; set; }
        public Nullable<double> planicidad_mm { get; set; }
        public string msa_hoda { get; set; }
        public Nullable<bool> requiere_consiliacion_puntas_colar { get; set; }
        public Nullable<double> scrap_permitido_puntas_colas { get; set; }
        public Nullable<System.DateTime> fecha_validez { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual proveedores proveedores { get; set; }
        public virtual proveedores proveedores1 { get; set; }
        public virtual SCDM_cat_clase_aprovisionamiento SCDM_cat_clase_aprovisionamiento { get; set; }
        public virtual SCDM_cat_diametro_interior SCDM_cat_diametro_interior { get; set; }
        public virtual SCDM_cat_disponentes SCDM_cat_disponentes { get; set; }
        public virtual SCDM_cat_ihs SCDM_cat_ihs { get; set; }
        public virtual SCDM_cat_ihs SCDM_cat_ihs1 { get; set; }
        public virtual SCDM_cat_ihs SCDM_cat_ihs2 { get; set; }
        public virtual SCDM_cat_ihs SCDM_cat_ihs3 { get; set; }
        public virtual SCDM_cat_ihs SCDM_cat_ihs4 { get; set; }
        public virtual SCDM_cat_modelo_negocio SCDM_cat_modelo_negocio { get; set; }
        public virtual SCDM_cat_molino SCDM_cat_molino { get; set; }
        public virtual SCDM_cat_parte_interior_exterior SCDM_cat_parte_interior_exterior { get; set; }
        public virtual SCDM_cat_peso_recubrimiento SCDM_cat_peso_recubrimiento { get; set; }
        public virtual SCDM_cat_posicion_rollo_embarques SCDM_cat_posicion_rollo_embarques { get; set; }
        public virtual SCDM_cat_tipo_materiales_solicitud SCDM_cat_tipo_materiales_solicitud { get; set; }
        public virtual SCDM_cat_tipo_metal SCDM_cat_tipo_metal { get; set; }
        public virtual SCDM_cat_tipo_recubrimiento SCDM_cat_tipo_recubrimiento { get; set; }
        public virtual SCDM_cat_tipo_transito SCDM_cat_tipo_transito { get; set; }
        public virtual SCDM_cat_tipo_venta SCDM_cat_tipo_venta { get; set; }
        public virtual SCDM_cat_unidades_medida SCDM_cat_unidades_medida { get; set; }
        public virtual SCDM_solicitud SCDM_solicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCDM_solicitud_rel_lista_tecnica> SCDM_solicitud_rel_lista_tecnica { get; set; }
        public virtual SCDM_solicitud_rel_lista_tecnica SCDM_solicitud_rel_lista_tecnica1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCDM_solicitud_rel_orden_compra> SCDM_solicitud_rel_orden_compra { get; set; }
    }
}
