//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCDM_cat_lovs_valuation_class
    {
        public int id { get; set; }
        public Nullable<int> id_SCDM_cat_modelo_negocio { get; set; }
        public Nullable<int> id_SCDM_cat_tipo_materiales_solicitud { get; set; }
        public Nullable<bool> esCM { get; set; }
        public string valuation_class { get; set; }
    
        public virtual SCDM_cat_modelo_negocio SCDM_cat_modelo_negocio { get; set; }
        public virtual SCDM_cat_tipo_materiales_solicitud SCDM_cat_tipo_materiales_solicitud { get; set; }
    }
}
