//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCDM_solicitud_item_material_datos_sap
    {
        public int id_scdm_solicitud_rel_item_material { get; set; }
        public string materiales_x_solicitud_ejecucion_correcta { get; set; }
        public string materiales_x_solicitud_mensaje_sap { get; set; }
        public string materiales_x_solicitud_nuevo_numero_material { get; set; }
        public string class_001_ejecucion_correcta { get; set; }
        public string class_001_mensaje_sap { get; set; }
        public string class_023_ejecucion_correcta { get; set; }
        public string class_023_mensaje_sap { get; set; }
        public string aum_ejecucion_correcta { get; set; }
        public string aum_mensaje_sap { get; set; }
        public string dp_ejecucion_correcta { get; set; }
        public string dp_mensaje_sap { get; set; }
        public string budget_ejecucion_correcta { get; set; }
        public string budget_mensaje_sap { get; set; }
    
        public virtual SCDM_solicitud_rel_item_material SCDM_solicitud_rel_item_material { get; set; }
    }
}
