//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCDM_solicitud_rel_extension_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCDM_solicitud_rel_extension_usuario()
        {
            this.SCDM_solicitud_rel_extension = new HashSet<SCDM_solicitud_rel_extension>();
            this.SCDM_solicitud_rel_extension_almacenes = new HashSet<SCDM_solicitud_rel_extension_almacenes>();
        }
    
        public int id { get; set; }
        public int id_solicitud { get; set; }
        public string material { get; set; }
        public string planta_referencia { get; set; }
        public string planta_destino { get; set; }
        public string ejecucion_correcta { get; set; }
        public string mensaje_sap { get; set; }
    
        public virtual SCDM_solicitud SCDM_solicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCDM_solicitud_rel_extension> SCDM_solicitud_rel_extension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCDM_solicitud_rel_extension_almacenes> SCDM_solicitud_rel_extension_almacenes { get; set; }
    }
}
