//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCDM_cat_usuarios_revision_departamento
    {
        public int id { get; set; }
        public int id_rel_usuarios_departamentos { get; set; }
        public int id_planta_solicitud { get; set; }
        public string tipo { get; set; }
        public bool activo { get; set; }
        public bool envia_correo { get; set; }
    
        public virtual SCDM_cat_rel_usuarios_departamentos SCDM_cat_rel_usuarios_departamentos { get; set; }
        public virtual plantas plantas { get; set; }
    }
}
