//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCDM_control_consecutivos
    {
        public int id { get; set; }
        public string nombre_secuencia { get; set; }
        public int ultimo_valor { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
    }
}
