//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCDM_solicitud_asignaciones
    {
        public int id { get; set; }
        public int id_solicitud { get; set; }
        public int id_departamento_asignacion { get; set; }
        public int id_empleado { get; set; }
        public System.DateTime fecha_asignacion { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public Nullable<System.DateTime> fecha_rechazo { get; set; }
        public string descripcion { get; set; }
        public string comentario_rechazo { get; set; }
        public Nullable<int> id_motivo_rechazo { get; set; }
        public Nullable<int> id_cierre { get; set; }
        public Nullable<int> id_rechazo { get; set; }
        public string comentario_scdm { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual empleados empleados1 { get; set; }
        public virtual empleados empleados2 { get; set; }
        public virtual SCDM_cat_departamentos_asignacion SCDM_cat_departamentos_asignacion { get; set; }
        public virtual SCDM_cat_motivo_rechazo SCDM_cat_motivo_rechazo { get; set; }
        public virtual SCDM_solicitud SCDM_solicitud { get; set; }
    }
}
