//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCDM_rel_secciones_por_tipo_solicitud
    {
        public int id { get; set; }
        public int id_tipo_solicitud { get; set; }
        public Nullable<int> id_tipo_cambio { get; set; }
        public int id_seccion { get; set; }
    
        public virtual SCDM_cat_secciones SCDM_cat_secciones { get; set; }
        public virtual SCDM_cat_tipo_cambio SCDM_cat_tipo_cambio { get; set; }
        public virtual SCDM_cat_tipo_solicitud SCDM_cat_tipo_solicitud { get; set; }
    }
}
