//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class upgrade_departamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public upgrade_departamentos()
        {
            this.upgrade_revision = new HashSet<upgrade_revision>();
        }
    
        public int id { get; set; }
        public int id_upgrade_planta { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
    
        public virtual upgrade_plantas upgrade_plantas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<upgrade_revision> upgrade_revision { get; set; }
    }
}
