//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class upgrade_revision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public upgrade_revision()
        {
            this.upgrade_values_checklist = new HashSet<upgrade_values_checklist>();
            this.upgrade_values_transaccion = new HashSet<upgrade_values_transaccion>();
        }
    
        public int id { get; set; }
        public int id_upgrade_usuario { get; set; }
        public int id_upgrade_departamento { get; set; }
        public bool activo { get; set; }
    
        public virtual upgrade_departamentos upgrade_departamentos { get; set; }
        public virtual upgrade_usuarios upgrade_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<upgrade_values_checklist> upgrade_values_checklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<upgrade_values_transaccion> upgrade_values_transaccion { get; set; }
    }
}
