//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class upgrade_values_checklist
    {
        public int id { get; set; }
        public int id_revision { get; set; }
        public int id_checklist_item { get; set; }
        public string estatus { get; set; }
        public string nota { get; set; }
        public bool activo { get; set; }
    
        public virtual upgrade_check_item upgrade_check_item { get; set; }
        public virtual upgrade_revision upgrade_revision { get; set; }
    }
}
