//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_SCDM_clientes_por_solictud
    {
        public long id { get; set; }
        public Nullable<int> id_solicitud { get; set; }
        public string sap_cliente { get; set; }
        public string nombre_cliente { get; set; }
    }
}
