//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_valores_fiscal_year
    {
        public long id { get; set; }
        public int id_budget_rel_fy_centro { get; set; }
        public int id_anio_fiscal { get; set; }
        public int id_centro_costo { get; set; }
        public int id_cuenta_sap { get; set; }
        public string sap_account { get; set; }
        public string name { get; set; }
        public string cost_center { get; set; }
        public string department { get; set; }
        public string class_1 { get; set; }
        public string class_2 { get; set; }
        public string responsable { get; set; }
        public string codigo_sap { get; set; }
        public int id_budget_plant { get; set; }
        public string mapping { get; set; }
        public string mapping_bridge { get; set; }
        public string currency_iso { get; set; }
        public Nullable<decimal> Enero { get; set; }
        public Nullable<decimal> Febrero { get; set; }
        public Nullable<decimal> Marzo { get; set; }
        public Nullable<decimal> Abril { get; set; }
        public Nullable<decimal> Mayo { get; set; }
        public Nullable<decimal> Junio { get; set; }
        public Nullable<decimal> Julio { get; set; }
        public Nullable<decimal> Agosto { get; set; }
        public Nullable<decimal> Septiembre { get; set; }
        public Nullable<decimal> Octubre { get; set; }
        public Nullable<decimal> Noviembre { get; set; }
        public Nullable<decimal> Diciembre { get; set; }
        public string Comentario { get; set; }
    }
}
