//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_historico_resultado
    {
        public long id { get; set; }
        public string Operador { get; set; }
        public string Supervisor { get; set; }
        public string SAP_Platina { get; set; }
        public string SAP_Platina_2 { get; set; }
        public string Tipo_de_Material { get; set; }
        public string Número_de_Parte__de_cliente { get; set; }
        public string SAP_Rollo { get; set; }
        public string Material { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Turno { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public string Orden_SAP { get; set; }
        public string Orden_en_SAP_2 { get; set; }
        public Nullable<double> Pieza_por_Golpe { get; set; }
        public string N__de_Rollo { get; set; }
        public string Lote_de_rollo { get; set; }
        public Nullable<double> Peso_Etiqueta__Kg_ { get; set; }
        public Nullable<double> Peso_de_regreso_de_rollo_Real { get; set; }
        public Nullable<double> Peso_de_rollo_usado { get; set; }
        public Nullable<double> Peso_Báscula_Kgs { get; set; }
        public Nullable<double> Piezas_por_paquete { get; set; }
        public Nullable<double> Total_de_piezas { get; set; }
        public Nullable<double> Peso_de_rollo_consumido { get; set; }
        public Nullable<double> Numero_de_golpes { get; set; }
        public Nullable<double> Kg_restante_de_rollo { get; set; }
        public Nullable<double> Peso_despunte_kgs_ { get; set; }
        public Nullable<double> Peso_cola_Kgs_ { get; set; }
        public Nullable<double> Porcentaje_de_puntas_y_colas { get; set; }
        public Nullable<double> Total_de_piezas_de_Ajustes { get; set; }
        public Nullable<double> Peso_Bruto_Kgs { get; set; }
        public Nullable<double> Peso_Real_Pieza_Bruto { get; set; }
        public Nullable<double> Peso_Real_Pieza_Neto { get; set; }
        public Nullable<double> Scrap_Natural { get; set; }
        public Nullable<double> Peso_neto_SAP { get; set; }
        public Nullable<double> Peso_Bruto_SAP { get; set; }
        public Nullable<double> Balance_de_Scrap { get; set; }
        public string Linea { get; set; }
        public string Planta { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<double> Column40 { get; set; }
        public Nullable<double> Ordenes_por_pieza { get; set; }
        public Nullable<double> Peso_de_rollo_usado_real__Kg { get; set; }
        public Nullable<double> Peso_bruto_Total_piezas_Kg { get; set; }
        public Nullable<double> Peso_NetoTotal_piezas_Kg { get; set; }
        public Nullable<double> Scrap_de_ingeniería__buenas___Ajuste__Total_Piezas_Kg { get; set; }
        public Nullable<double> Peso_Neto_total_piezas_de_ajuste_Kgs { get; set; }
        public Nullable<double> Peso_puntas_y_colas_reales_Kg { get; set; }
        public Nullable<double> Balance_de_Scrap_Real { get; set; }
        public string comentario { get; set; }
    }
}
