//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Materiales_Vencimiento
    {
        public string Material { get; set; }
        public string Planta { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento_Fin_De_Mes { get; set; }
        public Nullable<int> Dias_Para_Vencer { get; set; }
        public Nullable<int> ID_Solicitud_Origen { get; set; }
        public string Nombre_Solicitante { get; set; }
        public string Descripcion_Solicitud_Origen { get; set; }
        public string TipoDeVenta { get; set; }
        public string Cliente { get; set; }
    }
}
