// <auto-generated />
namespace Portal_2_0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IdEmpleado_Usuarios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdEmpleado_Usuarios));
        
        string IMigrationMetadata.Id
        {
            get { return "202110041536423_IdEmpleado_Usuarios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
