//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal_2_0.ServiceReferenceBasculas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBasculas.WebServiceBasculasSoap")]
    public interface WebServiceBasculasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ip del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PesoBascula", ReplyAction="*")]
        Portal_2_0.ServiceReferenceBasculas.PesoBasculaResponse PesoBascula(Portal_2_0.ServiceReferenceBasculas.PesoBasculaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PesoBascula", ReplyAction="*")]
        System.Threading.Tasks.Task<Portal_2_0.ServiceReferenceBasculas.PesoBasculaResponse> PesoBasculaAsync(Portal_2_0.ServiceReferenceBasculas.PesoBasculaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PesoBasculaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PesoBascula", Namespace="http://tempuri.org/", Order=0)]
        public Portal_2_0.ServiceReferenceBasculas.PesoBasculaRequestBody Body;
        
        public PesoBasculaRequest() {
        }
        
        public PesoBasculaRequest(Portal_2_0.ServiceReferenceBasculas.PesoBasculaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PesoBasculaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ip;
        
        public PesoBasculaRequestBody() {
        }
        
        public PesoBasculaRequestBody(string ip) {
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PesoBasculaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PesoBasculaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Portal_2_0.ServiceReferenceBasculas.PesoBasculaResponseBody Body;
        
        public PesoBasculaResponse() {
        }
        
        public PesoBasculaResponse(Portal_2_0.ServiceReferenceBasculas.PesoBasculaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PesoBasculaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PesoBasculaResult;
        
        public PesoBasculaResponseBody() {
        }
        
        public PesoBasculaResponseBody(string PesoBasculaResult) {
            this.PesoBasculaResult = PesoBasculaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceBasculasSoapChannel : Portal_2_0.ServiceReferenceBasculas.WebServiceBasculasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceBasculasSoapClient : System.ServiceModel.ClientBase<Portal_2_0.ServiceReferenceBasculas.WebServiceBasculasSoap>, Portal_2_0.ServiceReferenceBasculas.WebServiceBasculasSoap {
        
        public WebServiceBasculasSoapClient() {
        }
        
        public WebServiceBasculasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceBasculasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceBasculasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceBasculasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Portal_2_0.ServiceReferenceBasculas.PesoBasculaResponse Portal_2_0.ServiceReferenceBasculas.WebServiceBasculasSoap.PesoBascula(Portal_2_0.ServiceReferenceBasculas.PesoBasculaRequest request) {
            return base.Channel.PesoBascula(request);
        }
        
        public string PesoBascula(string ip) {
            Portal_2_0.ServiceReferenceBasculas.PesoBasculaRequest inValue = new Portal_2_0.ServiceReferenceBasculas.PesoBasculaRequest();
            inValue.Body = new Portal_2_0.ServiceReferenceBasculas.PesoBasculaRequestBody();
            inValue.Body.ip = ip;
            Portal_2_0.ServiceReferenceBasculas.PesoBasculaResponse retVal = ((Portal_2_0.ServiceReferenceBasculas.WebServiceBasculasSoap)(this)).PesoBascula(inValue);
            return retVal.Body.PesoBasculaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Portal_2_0.ServiceReferenceBasculas.PesoBasculaResponse> Portal_2_0.ServiceReferenceBasculas.WebServiceBasculasSoap.PesoBasculaAsync(Portal_2_0.ServiceReferenceBasculas.PesoBasculaRequest request) {
            return base.Channel.PesoBasculaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Portal_2_0.ServiceReferenceBasculas.PesoBasculaResponse> PesoBasculaAsync(string ip) {
            Portal_2_0.ServiceReferenceBasculas.PesoBasculaRequest inValue = new Portal_2_0.ServiceReferenceBasculas.PesoBasculaRequest();
            inValue.Body = new Portal_2_0.ServiceReferenceBasculas.PesoBasculaRequestBody();
            inValue.Body.ip = ip;
            return ((Portal_2_0.ServiceReferenceBasculas.WebServiceBasculasSoap)(this)).PesoBasculaAsync(inValue);
        }
    }
}
