use[Portal_2_0]
DROP VIEW IF EXISTS dbo.view_historico_resultado;  
/*****************************************************************************
*  Tipo de objeto: View
*  Funcion: Vista para mostrar el historico de resultados más nuevo
*  Autor :  Alfredo Xochitemol Cruz
*  Fecha de Creación: 11/02/2021
*  Log de Mantenimiento: 
*  Date          Modified By             Description            
*  ----------    --------------------    -------------------------------------
*  
******************************************************************************/
		
GO
CREATE VIEW [dbo].view_historico_resultado AS

SELECT 
	ISNULL(ROW_NUMBER() OVER (ORDER BY v2.fecha), 0) as id,
	v2.* FROM (SELECT v1.* FROM (
	
	SELECT distinct d2.* FROM(
	SELECT  [Operador ] as [Operador]
      ,[Supervisor ] as [Supervisor]
      ,[SAP Platina ] as [SAP Platina]
      ,[Tipo de Material]
      ,[Número de Parte  de cliente]
      ,[SAP Rollo]
      ,[Material]
      ,[Fecha]
      ,[Turno]
      ,[Hora ] AS [Hora]
      ,[Orden SAP]
      ,[Orden en SAP 2]
      ,[Pieza por Golpe]
      ,[N° de Rollo]
      ,CONVERT(varchar(256), CAST([Lote de rollo] AS decimal(10, 0))) AS [Lote de rollo]
      ,[Peso Etiqueta (Kg)]
	  ,CONVERT(float, CASE WHEN ISNUMERIC([Peso de regreso de rollo Real]) = 1 THEN [Peso de regreso de rollo Real] ELSE NULL END) AS [Peso de regreso de rollo Real]
      ,[Peso de rollo usado ] AS [Peso de rollo usado]
      ,[Peso Báscula Kgs]
      --,[N° Lote izquierdo]
      --,[N° Lote derecho]
      --,[#]
      ,[Piezas por paquete]
      ,[Total de piezas]
	  ,null AS [Peso de rollo consumido]
      ,[Numero de golpes]
      ,[Kg restante de rollo ] AS [Kg restante de rollo]
      ,[Peso despunte kgs#]
      ,[Peso cola Kgs#]
      ,[Porcentaje de puntas y colas]
     ,CONVERT(float, CASE WHEN ISNUMERIC([Total de piezas de Ajustes]) = 1 THEN [Total de piezas de Ajustes] ELSE NULL END) AS [Total de piezas de Ajustes]
      ,[Peso Bruto_Kgs]
      ,[Peso Real Pieza Bruto]
      ,[Peso Real Pieza Neto]
      ,[Scrap Natural]
      ,[Peso neto SAP]
      ,[Peso Bruto SAP]
      ,[Balance_de_Scrap]
      --,[Linea]
      ,ISNULL([Linea],SUBSTRING( [Operador ],1,10)) AS [Linea]
      ,ISNULL([Column38],'Puebla') as [Planta]
      ,YEAR(Fecha) AS [Anio]
      ,[Column40]
      ,[Ordenes por pieza]
      ,[Peso de rollo usado real _Kg]
      ,[Peso bruto Total piezas_Kg]
      ,[Peso NetoTotal piezas_Kg]
      ,[Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg]
      ,[Peso Neto_total piezas de ajuste_Kgs]
      ,[Peso puntas y colas reales_Kg]
      ,[Balance_de_Scrap_Real]
  FROM [cube_tkmm].[dbo].[view_union_bitacoras_puebla]
  )d2

  UNION ALL
  SELECT distinct d1.* FROM(
	SELECT [Operador]
      ,[Supervisor]
      ,[SAP Platina]
      ,[Tipo de Material]
      ,[Número de Parte  de cliente]
      ,[SAP Rollo]
      ,[Material]
      ,[Fecha]
      ,[Turno]
      ,[Hora]
      ,[Orden SAP]
      ,[Orden en SAP 2]
      ,[Pieza por Golpe]
      ,[N° de Rollo]
      ,CONVERT(varchar(256), CAST([Lote de rollo] AS decimal(10, 0))) AS [Lote de rollo]
      ,[Peso Etiqueta (Kg)]
      ,CONVERT(float, CASE WHEN ISNUMERIC([Peso de regreso de rollo Real]) = 1 THEN [Peso de regreso de rollo Real] ELSE NULL END) AS [Peso de regreso de rollo Real]
      ,[Peso de rollo usado]
      ,[Peso Báscula Kgs]
      --,[N° Lote izquierdo]
      --,[N° Lote derecho]
      --,[#]
      ,[Piezas por paquete]
      ,[Total de piezas]
      ,[Peso de rollo consumido]
	  ,null as [Numero de golpes]
      ,null as [Kg restante de rollo]
      ,[Peso despunte kgs#]
      ,[Peso cola Kgs#]
      ,[Porcentaje de puntas y colas]
      ,[Total de piezas de Ajustes]
      ,[Peso Bruto Kgs]
      ,[Peso Real Pieza Bruto]
      ,[Peso Real Pieza Neto]
      ,[Scrap Natural]
      ,[Peso neto SAP]
      ,[Peso Bruto SAP]
      ,[Balance de Scrap]
	 -- ,null as [Linea]
      ,ISNULL([Column37],SUBSTRING( [Operador],1,10)) AS [Linea]
      ,ISNULL([Column38],'Silao') as [Planta]
      ,YEAR(Fecha) AS [Anio]
      ,[Column40]
      ,[Ordenes por pieza]
      ,[Peso de rollo usado real _Kg]
      ,[Peso bruto Total piezas_Kg]
      ,[Peso NetoTotal piezas_Kg]
      ,[Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg]
      ,[Peso Neto_total piezas de ajuste_Kgs]
      ,[Peso puntas y colas reales_Kg]
      ,[Balance_de_Scrap_Real]
  FROM [cube_tkmm].[dbo].[view_union_bitacoras_silao]
  )d1

 ) v1

 UNION ALL

SELECT TOP (100) 
		--[id]
      [Operador]
      ,[Supervisor]
      ,[SAP Platina]
      ,[Tipo de Material]
      ,[Número de Parte de Cliente]
      ,[SAP Rollo]
      ,[Material]
      ,[Fecha]
      ,[Turno]
      ,[Hora]
      ,[Orden SAP]
      ,[Orden en SAP 2]
      ,[Pieza por Golpe]
      ,[N° de Rollo]
      ,CONVERT(varchar(256), CAST([Lote de rollo] AS decimal(10, 0))) AS [Lote de rollo]
      ,[Peso Etiqueta (Kg)]
      ,[Peso de regreso de rollo Real]
      ,[Peso de rollo usado ]
      ,[Peso Báscula Kgs]
      --,[N° Lote izquierdo]
      --,[N° Lote derecho]
      --,[#]
      ,[Piezas por paquete]
      ,[Total de piezas]
	  ,null AS [Peso de rollo consumido]
      ,[Numero de golpes]
      ,[Kg restante de rollo]
      ,[Peso despunte kgs#]
      ,[Peso cola Kgs#]
      ,[Porcentaje de puntas y colas]
      ,[Total de piezas de Ajustes]
      ,[Peso Bruto Kgs]
      ,[Peso Real Pieza Bruto]
      ,[Peso Real Pieza Neto]
      ,[Scrap Natural]
      ,[Peso neto SAP]
      ,[Peso Bruto SAP]
      ,[Balance de Scrap]
      ,[Column37] AS [Linea]
      ,[Column38] AS [Planta]
      ,[Column39] AS [Anio]
      ,[Column40]
      ,[Ordenes por pieza]
      ,[Peso de rollo usado real _Kg]
      ,[Peso bruto Total piezas_Kg]
      ,[Peso NetoTotal piezas_Kg]
      ,[Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg]
      ,[Peso Neto_total piezas de ajuste_Kgs]
      ,[Peso puntas y colas reales_Kg]
      ,[Balance_de_Scrap_Real]
  FROM [Portal_2_0].[dbo].[view_produccion_resultados])v2
	WHERE Fecha is not null