
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*****************************************************************************
*  Tipo de objeto:     Alter table
*  Autor :  Alfredo Xochitemol
*  Fecha de Creación: 
*  Log de Mantenimiento: 
*  Date          Modified By             Description            
*  ----------    --------------------    -------------------------------------
*  24/08/2022	Alfredo Xochitemol		Agrega campo para definir jefe directo
******************************************************************************/

BEGIN TRANSACTION
		IF object_id(N'empleados','U') IS NOT NULL
		BEGIN
			ALTER TABLE empleados ADD id_jefe_directo INT NULL
			PRINT 'Se ha creado la columna id_jefe_directo en la tabla empleados'
			
			  -- restriccion de clave foranea
			alter table [empleados]
			 add constraint FK_empleados_jefe_directo
			  foreign key (id_jefe_directo)
			  references empleados(id);
		END
		ELSE
		BEGIN
			PRINT 'La tabla empleados NO EXISTE, no se puede crear las columnas'
		END


		--inserts
		GO
		update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '1') WHERE numeroEmpleado = '1'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10001'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10004'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20124') WHERE numeroEmpleado = '10008'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20124') WHERE numeroEmpleado = '10011'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20124') WHERE numeroEmpleado = '10012'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10022'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10024'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10026'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20320') WHERE numeroEmpleado = '10028'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10032'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10035'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10038'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10040'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10041'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20124') WHERE numeroEmpleado = '10050'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10054'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20124') WHERE numeroEmpleado = '10060'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10068'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20326') WHERE numeroEmpleado = '10073'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20023') WHERE numeroEmpleado = '10075'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20320') WHERE numeroEmpleado = '10093'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10096'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20326') WHERE numeroEmpleado = '10098'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10116'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10135'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20326') WHERE numeroEmpleado = '10150'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20320') WHERE numeroEmpleado = '10157'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10160'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10165'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20025') WHERE numeroEmpleado = '10168'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10175'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20320') WHERE numeroEmpleado = '10193'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10207'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20327') WHERE numeroEmpleado = '10223'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10225'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10227'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10232'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20025') WHERE numeroEmpleado = '10240'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10252'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10254'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10264'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20124') WHERE numeroEmpleado = '10265'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10266'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20025') WHERE numeroEmpleado = '10276'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20327') WHERE numeroEmpleado = '10301'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10306'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '40008') WHERE numeroEmpleado = '10310'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10313'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10316'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20362') WHERE numeroEmpleado = '10320'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20023') WHERE numeroEmpleado = '10327'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20362') WHERE numeroEmpleado = '10340'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10344'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20025') WHERE numeroEmpleado = '10349'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20327') WHERE numeroEmpleado = '10352'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10358'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20327') WHERE numeroEmpleado = '10360'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '40007') WHERE numeroEmpleado = '10363'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20326') WHERE numeroEmpleado = '10366'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20326') WHERE numeroEmpleado = '10373'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10385'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20327') WHERE numeroEmpleado = '10386'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20025') WHERE numeroEmpleado = '10389'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20327') WHERE numeroEmpleado = '10390'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20327') WHERE numeroEmpleado = '10392'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20326') WHERE numeroEmpleado = '10393'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20362') WHERE numeroEmpleado = '10394'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20124') WHERE numeroEmpleado = '10396'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20221') WHERE numeroEmpleado = '10397'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20124') WHERE numeroEmpleado = '10398'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20124') WHERE numeroEmpleado = '10399'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20336') WHERE numeroEmpleado = '10400'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '1') WHERE numeroEmpleado = '20006'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20137') WHERE numeroEmpleado = '20007'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20235') WHERE numeroEmpleado = '20008'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20235') WHERE numeroEmpleado = '20010'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20235') WHERE numeroEmpleado = '20012'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20021'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20029') WHERE numeroEmpleado = '20023'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20284') WHERE numeroEmpleado = '20025'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20235') WHERE numeroEmpleado = '20029'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20031'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20235') WHERE numeroEmpleado = '20033'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20035'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20137') WHERE numeroEmpleado = '20037'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20129') WHERE numeroEmpleado = '20043'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20029') WHERE numeroEmpleado = '20048'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20033') WHERE numeroEmpleado = '20057'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20061'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '1') WHERE numeroEmpleado = '20066'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20074'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20075'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20240') WHERE numeroEmpleado = '20082'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20084'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20087'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20010') WHERE numeroEmpleado = '20089'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20095'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20101'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20235') WHERE numeroEmpleado = '20104'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20200') WHERE numeroEmpleado = '20105'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20137') WHERE numeroEmpleado = '20111'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20116'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20119'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20131') WHERE numeroEmpleado = '20120'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20284') WHERE numeroEmpleado = '20124'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20235') WHERE numeroEmpleado = '20129'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20155') WHERE numeroEmpleado = '20131'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20364') WHERE numeroEmpleado = '20134'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '1') WHERE numeroEmpleado = '20137'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20137') WHERE numeroEmpleado = '20138'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20142'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20129') WHERE numeroEmpleado = '20147'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20150'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '1') WHERE numeroEmpleado = '20155'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20200') WHERE numeroEmpleado = '20157'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20200') WHERE numeroEmpleado = '20174'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20029') WHERE numeroEmpleado = '20183'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20033') WHERE numeroEmpleado = '20190'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20198'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20104') WHERE numeroEmpleado = '20200'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20104') WHERE numeroEmpleado = '20202'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20012') WHERE numeroEmpleado = '20206'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20129') WHERE numeroEmpleado = '20214'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20010') WHERE numeroEmpleado = '20221'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20012') WHERE numeroEmpleado = '20228'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20200') WHERE numeroEmpleado = '20231'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20104') WHERE numeroEmpleado = '20232'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20291') WHERE numeroEmpleado = '20235'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20274') WHERE numeroEmpleado = '20240'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20129') WHERE numeroEmpleado = '20245'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20012') WHERE numeroEmpleado = '20257'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20274') WHERE numeroEmpleado = '20261'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20320') WHERE numeroEmpleado = '20265'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20131') WHERE numeroEmpleado = '20267'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20240') WHERE numeroEmpleado = '20269'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20274') WHERE numeroEmpleado = '20270'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '1') WHERE numeroEmpleado = '20274'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20240') WHERE numeroEmpleado = '20275'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20274') WHERE numeroEmpleado = '20279'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20279') WHERE numeroEmpleado = '20282'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20279') WHERE numeroEmpleado = '20283'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20235') WHERE numeroEmpleado = '20284'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20270') WHERE numeroEmpleado = '20290'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '1') WHERE numeroEmpleado = '20291'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20033') WHERE numeroEmpleado = '20292'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20320') WHERE numeroEmpleado = '20297'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20320') WHERE numeroEmpleado = '20299'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20124') WHERE numeroEmpleado = '20303'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20291') WHERE numeroEmpleado = '20306'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20307'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20131') WHERE numeroEmpleado = '20309'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20131') WHERE numeroEmpleado = '20311'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20269') WHERE numeroEmpleado = '20312'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '1') WHERE numeroEmpleado = '20315'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20279') WHERE numeroEmpleado = '20316'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20010') WHERE numeroEmpleado = '20320'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20284') WHERE numeroEmpleado = '20326'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20284') WHERE numeroEmpleado = '20327'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20279') WHERE numeroEmpleado = '20328'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20200') WHERE numeroEmpleado = '20331'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20124') WHERE numeroEmpleado = '20332'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20029') WHERE numeroEmpleado = '20336'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20131') WHERE numeroEmpleado = '20340'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20274') WHERE numeroEmpleado = '20341'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20341') WHERE numeroEmpleado = '20344'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20315') WHERE numeroEmpleado = '20345'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20291') WHERE numeroEmpleado = '20346'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20010') WHERE numeroEmpleado = '20348'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20010') WHERE numeroEmpleado = '20349'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20320') WHERE numeroEmpleado = '20352'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20124') WHERE numeroEmpleado = '20353'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20291') WHERE numeroEmpleado = '20357'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20341') WHERE numeroEmpleado = '20359'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20315') WHERE numeroEmpleado = '20360'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20315') WHERE numeroEmpleado = '20361'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20284') WHERE numeroEmpleado = '20362'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20200') WHERE numeroEmpleado = '20363'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20155') WHERE numeroEmpleado = '20364'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20240') WHERE numeroEmpleado = '20365'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20341') WHERE numeroEmpleado = '20367'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20364') WHERE numeroEmpleado = '20368'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20008') WHERE numeroEmpleado = '20369'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20364') WHERE numeroEmpleado = '20370'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20261') WHERE numeroEmpleado = '20371'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20364') WHERE numeroEmpleado = '20372'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '1') WHERE numeroEmpleado = '20373'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20274') WHERE numeroEmpleado = '20374'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20341') WHERE numeroEmpleado = '20375'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20010') WHERE numeroEmpleado = '20377'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20365') WHERE numeroEmpleado = '20378'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20137') WHERE numeroEmpleado = '20379'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20006') WHERE numeroEmpleado = '20380'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '40007') WHERE numeroEmpleado = '30005'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20124') WHERE numeroEmpleado = '30007'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '40007') WHERE numeroEmpleado = '30010'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '40007') WHERE numeroEmpleado = '40006'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20284') WHERE numeroEmpleado = '40007'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '40007') WHERE numeroEmpleado = '40008'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20373') WHERE numeroEmpleado = '60002'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20315') WHERE numeroEmpleado = '20278'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '20288'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70066'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70086'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70095'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70110'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70138'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70147'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70154'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70158'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70174'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70189'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70200'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70207'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70222'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70245'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70249'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70253'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70290'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70313'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70333'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70345'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70349'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70355'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70357'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70360'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70369'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70373'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70376'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70379'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70386'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70393'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70400'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70406'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70407'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70411'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70413'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70416'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70420'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70425'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '70430'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70441'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70456'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70465'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70466'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70469'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70470'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70484'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70490'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70504'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70506'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70511'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70526'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70533'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70538'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '70540'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70542'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '70543'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70545'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70546'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70549'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70551'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70560'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70561'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70565'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70570'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70571'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70575'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70576'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70578'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70581'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70584'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70585'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70586'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70587'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70588'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70610'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70617'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70624'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70630'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70631'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70632'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70638'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70641'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70643'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70645'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70647'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70649'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70651'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70655'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70658'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70659'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70660'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70661'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '70663'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70664'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '70665'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '80002'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80021'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80039'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20291') WHERE numeroEmpleado = '80060'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80060') WHERE numeroEmpleado = '80068'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80060') WHERE numeroEmpleado = '80072'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80088'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80090'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80093'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80094'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '80104'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80130') WHERE numeroEmpleado = '80114'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80115'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80060') WHERE numeroEmpleado = '80130'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80130') WHERE numeroEmpleado = '80133'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80141'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80146'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80149'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80060') WHERE numeroEmpleado = '80156'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80072') WHERE numeroEmpleado = '80157'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '80158'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '80163'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '80164'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80168'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80188'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80196'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '80205'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80207'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80210'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80213'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80214'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80218'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80221'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '80227'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80231'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80235'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80060') WHERE numeroEmpleado = '80236'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80241'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80243'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '80248'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80249'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '80250'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80130') WHERE numeroEmpleado = '80254'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80264') WHERE numeroEmpleado = '80258'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80260'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80060') WHERE numeroEmpleado = '80264'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80264') WHERE numeroEmpleado = '80268'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80060') WHERE numeroEmpleado = '80269'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80274'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '80275'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80276'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80277'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '80279'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '80280'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80281'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80283'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80285'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80286'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80287'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '80291'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80292'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80294'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80297'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80298'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20364') WHERE numeroEmpleado = '80299'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80301'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80307'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '80308'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80314'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80315'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80317'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '80318'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80319'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80320'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80264') WHERE numeroEmpleado = '80322'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20291') WHERE numeroEmpleado = '80323'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80324'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80326'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20270') WHERE numeroEmpleado = '80332'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '80335'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80341'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80343'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80346'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80347'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80348'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80357') WHERE numeroEmpleado = '80349'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80350'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80269') WHERE numeroEmpleado = '80351'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80356'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80060') WHERE numeroEmpleado = '80357'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80072') WHERE numeroEmpleado = '80358'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80068') WHERE numeroEmpleado = '80359'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80361'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80156') WHERE numeroEmpleado = '80362'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80264') WHERE numeroEmpleado = '80364'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20291') WHERE numeroEmpleado = '80366'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20278') WHERE numeroEmpleado = '80367'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20357') WHERE numeroEmpleado = '80368'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '20270') WHERE numeroEmpleado = '80369'
update empleados set id_jefe_directo = (SELECT TOP 1 id from empleados where numeroEmpleado = '80236') WHERE numeroEmpleado = '80370'


		GO

COMMIT TRANSACTION

GO
