use[Portal_2_0]
DROP VIEW IF EXISTS dbo.view_historico_resultado;  
/*****************************************************************************
*  Tipo de objeto: View
*  Funcion: Vista para mostrar el historico de resultados más nuevo
*  Autor :  Alfredo Xochitemol Cruz
*  Fecha de Creación: 11/02/2021
*  Log de Mantenimiento: 
*  Date          Modified By             Description            
*  ----------    --------------------    -------------------------------------
*  
******************************************************************************/
		
GO
CREATE VIEW [dbo].view_historico_resultado AS

SELECT
	ISNULL(ROW_NUMBER() OVER (ORDER BY v3.fecha, v3.[SAP Platina] desc), 0) as id,
	v3.*,
	(SELECT comentarios from dbo.produccion_datos_entrada where v3.Column40>0 AND id_produccion_registro =v3.Column40) as comentario
	FROM (
SELECT       
      [operador] AS [Operador]
      ,[supervisor] as [Supervisor]
      ,[sap_platina] as [SAP Platina]
	  ,null as [SAP Platina 2]
      ,[tipo_material] AS [Tipo de Material]
      ,[numero_parte_cliente] AS [Número de Parte  de cliente]
      ,[sap_rollo] AS [SAP Rollo]
      ,[material] AS [Material]
	  , CASE
            WHEN DATEPART(HOUR, fecha) = 0 AND DATEPART(MINUTE, fecha)= 0 AND  DATEPART(SECOND, fecha)= 0
               THEN  DATEADD(HOUR, DATEPART(HOUR, hora),  DATEADD(MINUTE, DATEPART(MINUTE, hora), DATEADD(SECOND, DATEPART(SECOND, hora), fecha))  ) 
               ELSE fecha
       END as [Fecha]
      --,[fecha] AS [Fecha]
      ,[turno] AS [Turno]
      ,[hora] AS [Hora]
      ,[orden_sap] AS [Orden SAP]
      ,[orden_sap_2] AS [Orden en SAP 2]
      ,[pieza_por_golpe] AS [Pieza por Golpe]
      ,[numero_rollo] AS [N° de Rollo]
      ,[lote_rollo] AS [Lote de rollo]
      ,[peso_etiqueta] AS [Peso Etiqueta (Kg)]
      ,[peso_regreso_rollo_real] AS [Peso de regreso de rollo Real]
      ,[peso_rollo_usado] AS [Peso de rollo usado]
      ,[peso_bascula_kgs] AS [Peso Báscula Kgs]
      ,[piezas_por_paquete] AS [Piezas por paquete]
      ,[total_piezas] AS [Total de piezas]
      ,[peso_rollo_consumido] AS [Peso de rollo consumido]
      ,[numero_golpes] AS [Numero de golpes]
	  ,null AS  [Kg restante de rollo]
      ,[peso_despunte_kgs] AS [Peso despunte kgs#]
      ,[peso_cola_kgs] AS [Peso cola Kgs#]
      ,[porcentaje_punta_y_colas] AS [Porcentaje de puntas y colas]
      ,[total_piezas_ajuste] AS [Total de piezas de Ajustes]
      ,[peso_bruto_kgs] AS [Peso Bruto_Kgs]
      ,[peso_real_pieza_bruto] AS [Peso Real Pieza Bruto]
      ,[peso_real_pieza_neto] AS [Peso Real Pieza Neto]
      ,[scrap_natural] AS [Scrap Natural]
      ,[peso_neto_sap] AS [Peso neto SAP]
      ,[peso_bruto_sap] AS [Peso Bruto SAP]
      ,[balance_scrap] AS [Balance_de_Scrap]
	  ,[linea] AS [Linea]
	  ,[planta] AS [Planta]      
	  ,YEAR(fecha) AS [Anio]
	  ,null as [Column40]
	  ,[ordenes_por_pieza] AS [Ordenes por pieza]
      ,[peso_rollo_usado_real_kgs] AS [Peso de rollo usado real _Kg]
      ,[peso_bruto_total_piezas_kgs] AS [Peso bruto Total piezas_Kg]
      ,[peso_neto_total_piezas_kgs] AS [Peso NetoTotal piezas_Kg]
      ,[scrap_ingenieria_buenas_mas_ajuste] AS [Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg]
      ,[peso_neto_total_piezas_ajuste] AS [Peso Neto_total piezas de ajuste_Kgs]
      ,[peso_punta_y_colas_reales] AS  [Peso puntas y colas reales_Kg]
      ,[balance_scrap_real] AS [Balance_de_Scrap_Real]
	  --nuevos campos
	  ,null as [Tipo de Material_platina2]
	  ,null as [Número de Parte de Cliente_platina2]
	  ,null as [Material_platina2]
	  ,null as [Total de piezas_platina1]
	  ,null as [Total de piezas_platina2]
	  ,null as [Total de piezas de Ajustes_platina1]
	  ,null as [Total de piezas de Ajustes_platina2]
	     --platina 2
	  ,null as [Peso Bruto Kgs_platina2]	
	  ,null as [Peso Real Pieza Bruto_platina2]
	  ,null as [Peso Real Pieza Neto_platina2]		
	  ,null as [Scrap Natural_platina2]
	  ,null as [Peso neto SAP_platina2]
	  ,null as [Peso Bruto SAP_platina2]
	  ,null as [Balance de Scrap_platina2]	
	  ,null as [Peso de rollo usado real _Kg_platina2]	
	  ,null as [Peso bruto Total piezas_Kg_platina2]		
	  ,null as [Peso NetoTotal piezas_Kg_platina2]
	  ,null as [Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg_platina2]	
	  ,null as [Peso Neto_total piezas de ajuste_Kgs_platina2]
	  ,null as [Peso puntas y colas reales_Kg_platina2]			
	  ,null as [Balance_de_Scrap_Real_platina2]
	  --general
	  ,[peso_bruto_kgs] as [Peso Bruto Kgs_general]	
	  ,[peso_real_pieza_bruto] AS [Peso Real Pieza Bruto_general]
      ,[peso_real_pieza_neto] AS [Peso Real Pieza Neto_general]
	  ,[scrap_natural] as [Scrap Natural_general]
	  ,[peso_neto_sap] as [Peso neto SAP_general]
	  ,[peso_bruto_sap] as [Peso Bruto SAP_general]
	  ,[balance_scrap] as [Balance de Scrap_general]	
	  ,[peso_rollo_usado_real_kgs] as [Peso de rollo usado real _Kg_general]	
	  ,[peso_bruto_total_piezas_kgs] as [Peso bruto Total piezas_Kg_general]		
	  ,[peso_neto_total_piezas_kgs] as [Peso NetoTotal piezas_Kg_general]
	  ,[scrap_ingenieria_buenas_mas_ajuste] as [Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg_general]	
	  ,[peso_neto_total_piezas_ajuste] as [Peso Neto_total piezas de ajuste_Kgs_general]
	  ,[peso_punta_y_colas_reales] as [Peso puntas y colas reales_Kg_general]			
	  ,[balance_scrap_real] as [Balance_de_Scrap_Real_general]
  FROM [dbo].[produccion_respaldo]

  UNION ALL

SELECT
	--ISNULL(ROW_NUMBER() OVER (ORDER BY v2.fecha), 0) as id,
	v2.* FROM (SELECT v1.* FROM (
	
	SELECT distinct d2.* FROM(
	SELECT  [Operador ] as [Operador]
      ,[Supervisor ] as [Supervisor]
      ,[SAP Platina ] as [SAP Platina]
	  ,null as [SAP Platina 2]
      ,[Tipo de Material]
      ,[Número de Parte  de cliente]
      ,[SAP Rollo]
      ,[Material]
      , CASE
            WHEN DATEPART(HOUR, fecha) = 0 AND DATEPART(MINUTE, fecha)= 0 AND  DATEPART(SECOND, fecha)= 0
               THEN  DATEADD(HOUR, DATEPART(HOUR, [Hora ]),  DATEADD(MINUTE, DATEPART(MINUTE, [Hora ]), DATEADD(SECOND, DATEPART(SECOND, [Hora ]), fecha))  ) 
               ELSE fecha
       END as [Fecha]
      --,[fecha] AS [Fecha]
      ,[Turno]
      ,[Hora ] AS [Hora]
      ,[Orden SAP]
      ,[Orden en SAP 2]
      ,[Pieza por Golpe]
      ,[N° de Rollo]
      ,CONVERT(varchar(256), CAST([Lote de rollo] AS decimal(10, 0))) AS [Lote de rollo]
      ,[Peso Etiqueta (Kg)]
	  ,CONVERT(float, CASE WHEN ISNUMERIC([Peso de regreso de rollo Real]) = 1 THEN [Peso de regreso de rollo Real] ELSE NULL END) AS [Peso de regreso de rollo Real]
      ,[Peso de rollo usado ] AS [Peso de rollo usado]
      ,[Peso Báscula Kgs]
      --,[N° Lote izquierdo]
      --,[N° Lote derecho]
      --,[#]
      ,[Piezas por paquete]
      ,[Total de piezas]
	  ,null AS [Peso de rollo consumido]
      ,[Numero de golpes]
      ,[Kg restante de rollo ] AS [Kg restante de rollo]
      ,[Peso despunte kgs#]
      ,[Peso cola Kgs#]
      ,[Porcentaje de puntas y colas]
     ,CONVERT(float, CASE WHEN ISNUMERIC([Total de piezas de Ajustes]) = 1 THEN [Total de piezas de Ajustes] ELSE NULL END) AS [Total de piezas de Ajustes]
      ,[Peso Bruto_Kgs]
      ,[Peso Real Pieza Bruto]
      ,[Peso Real Pieza Neto]
      ,[Scrap Natural]
      ,[Peso neto SAP]
      ,[Peso Bruto SAP]
      ,[Balance_de_Scrap]
      --,[Linea]
      ,ISNULL([Linea],SUBSTRING( [Operador ],1,10)) AS [Linea]
      ,ISNULL([Column38],'Puebla') as [Planta]
      ,YEAR(Fecha) AS [Anio]
      ,null as [Column40]
      ,[Ordenes por pieza]
      ,[Peso de rollo usado real _Kg]
      ,[Peso bruto Total piezas_Kg]
      ,[Peso NetoTotal piezas_Kg]
      ,[Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg]
      ,[Peso Neto_total piezas de ajuste_Kgs]
      ,[Peso puntas y colas reales_Kg]
      ,[Balance_de_Scrap_Real]
	  --nuevos campos
	  ,null as [Tipo de Material_platina2]
	  ,null as [Número de Parte de Cliente_platina2]
	  ,null as [Material_platina2]
      ,null as [Total de piezas_platina1]
	  ,null as [Total de piezas_platina2]
	  ,null as [Total de piezas de Ajustes_platina1]
	  ,null as [Total de piezas de Ajustes_platina2]
	     --platina 2
	  ,null as [Peso Bruto Kgs_platina2]	
	  ,null as [Peso Real Pieza Bruto_platina2]
	  ,null as [Peso Real Pieza Neto_platina2]		
	  ,null as [Scrap Natural_platina2]
	  ,null as [Peso neto SAP_platina2]
	  ,null as [Peso Bruto SAP_platina2]
	  ,null as [Balance de Scrap_platina2]	
	  ,null as [Peso de rollo usado real _Kg_platina2]	
	  ,null as [Peso bruto Total piezas_Kg_platina2]		
	  ,null as [Peso NetoTotal piezas_Kg_platina2]
	  ,null as [Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg_platina2]	
	  ,null as [Peso Neto_total piezas de ajuste_Kgs_platina2]
	  ,null as [Peso puntas y colas reales_Kg_platina2]			
	  ,null as [Balance_de_Scrap_Real_platina2]
	  --general
	  ,[Peso Bruto_Kgs] as [Peso Bruto Kgs_general]	
	  ,[Peso Real Pieza Bruto] AS [Peso Real Pieza Bruto_general]
      ,[Peso Real Pieza Neto] AS [Peso Real Pieza Neto_general]
	  ,[Scrap Natural] as [Scrap Natural_general]
	  ,[Peso neto SAP] as [Peso neto SAP_general]
	  ,[Peso Bruto SAP] as [Peso Bruto SAP_general]
	  ,[Balance_de_Scrap] as [Balance de Scrap_general]	
	  ,[Peso de rollo usado real _Kg] as [Peso de rollo usado real _Kg_general]	
	  ,[Peso bruto Total piezas_Kg] as [Peso bruto Total piezas_Kg_general]		
	  ,[Peso NetoTotal piezas_Kg] as [Peso NetoTotal piezas_Kg_general]
	  ,[Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg] as [Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg_general]	
	  ,[Peso Neto_total piezas de ajuste_Kgs] as [Peso Neto_total piezas de ajuste_Kgs_general]
	  ,[Peso puntas y colas reales_Kg] as [Peso puntas y colas reales_Kg_general]			
	  ,[Balance_de_Scrap_Real] as [Balance_de_Scrap_Real_general]
  FROM [cube_tkmm].[dbo].[view_union_bitacoras_puebla]
  )d2

  UNION ALL
  SELECT distinct d1.* FROM(
	SELECT [Operador]
      ,[Supervisor]
      ,[SAP Platina]
	   ,null as [SAP Platina 2]
      ,[Tipo de Material]
      ,[Número de Parte  de cliente]
      ,[SAP Rollo]
      ,[Material]
       , CASE
            WHEN DATEPART(HOUR, fecha) = 0 AND DATEPART(MINUTE, fecha)= 0 AND  DATEPART(SECOND, fecha)= 0
               THEN  DATEADD(HOUR, DATEPART(HOUR, [Hora]),  DATEADD(MINUTE, DATEPART(MINUTE, [Hora]), DATEADD(SECOND, DATEPART(SECOND, [Hora]), fecha))  ) 
               ELSE fecha
       END as [Fecha]
      --,[fecha] AS [Fecha]
      ,[Turno]
      ,[Hora]
      ,[Orden SAP]
      ,[Orden en SAP 2]
      ,[Pieza por Golpe]
      ,[N° de Rollo]
      ,CONVERT(varchar(256), CAST([Lote de rollo] AS decimal(10, 0))) AS [Lote de rollo]
      ,[Peso Etiqueta (Kg)]
      ,CONVERT(float, CASE WHEN ISNUMERIC([Peso de regreso de rollo Real]) = 1 THEN [Peso de regreso de rollo Real] ELSE NULL END) AS [Peso de regreso de rollo Real]
      ,[Peso de rollo usado]
      ,[Peso Báscula Kgs]
      --,[N° Lote izquierdo]
      --,[N° Lote derecho]
      --,[#]
      ,[Piezas por paquete]
      ,[Total de piezas]
      ,[Peso de rollo consumido]
	  ,null as [Numero de golpes]
      ,null as [Kg restante de rollo]
      ,[Peso despunte kgs#]
      ,[Peso cola Kgs#]
      ,[Porcentaje de puntas y colas]
      ,[Total de piezas de Ajustes]
      ,[Peso Bruto Kgs]
      ,[Peso Real Pieza Bruto]
      ,[Peso Real Pieza Neto]
      ,[Scrap Natural]
      ,[Peso neto SAP]
      ,[Peso Bruto SAP]
      ,[Balance de Scrap]
	 -- ,null as [Linea]
      ,ISNULL([Column37],SUBSTRING( [Operador],1,10)) AS [Linea]
      ,ISNULL([Column38],'Silao') as [Planta]
      ,YEAR(Fecha) AS [Anio]
      ,null as [Column40]
      ,[Ordenes por pieza]
      ,[Peso de rollo usado real _Kg]
      ,[Peso bruto Total piezas_Kg]
      ,[Peso NetoTotal piezas_Kg]
      ,[Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg]
      ,[Peso Neto_total piezas de ajuste_Kgs]
      ,[Peso puntas y colas reales_Kg]
      ,[Balance_de_Scrap_Real]
	  --nuevos campos
	  ,null as [Tipo de Material_platina2]
	  ,null as [Número de Parte de Cliente_platina2]
	  ,null as [Material_platina2]
	  ,null as [Total de piezas_platina1]
	  ,null as [Total de piezas_platina2]
	  ,null as [Total de piezas de Ajustes_platina1]
	  ,null as [Total de piezas de Ajustes_platina2]
	   --platina 2
	  ,null as [Peso Bruto Kgs_platina2]	
	  ,null as [Peso Real Pieza Bruto_platina2]
	  ,null as [Peso Real Pieza Neto_platina2]		
	  ,null as [Scrap Natural_platina2]
	  ,null as [Peso neto SAP_platina2]
	  ,null as [Peso Bruto SAP_platina2]
	  ,null as [Balance de Scrap_platina2]	
	  ,null as [Peso de rollo usado real _Kg_platina2]	
	  ,null as [Peso bruto Total piezas_Kg_platina2]		
	  ,null as [Peso NetoTotal piezas_Kg_platina2]
	  ,null as [Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg_platina2]	
	  ,null as [Peso Neto_total piezas de ajuste_Kgs_platina2]
	  ,null as [Peso puntas y colas reales_Kg_platina2]			
	  ,null as [Balance_de_Scrap_Real_platina2]
	  --general
	  ,[Peso Bruto Kgs] as [Peso Bruto Kgs_general]	
	  ,[Peso Real Pieza Bruto] AS [Peso Real Pieza Bruto_general]
      ,[Peso Real Pieza Neto] AS [Peso Real Pieza Neto_general]
	  ,[Scrap Natural] as [Scrap Natural_general]
	  ,[Peso neto SAP] as [Peso neto SAP_general]
	  ,[Peso Bruto SAP] as [Peso Bruto SAP_general]
	  ,[Balance de Scrap] as [Balance de Scrap_general]	
	  ,[Peso de rollo usado real _Kg] as [Peso de rollo usado real _Kg_general]	
	  ,[Peso bruto Total piezas_Kg] as [Peso bruto Total piezas_Kg_general]		
	  ,[Peso NetoTotal piezas_Kg] as [Peso NetoTotal piezas_Kg_general]
	  ,[Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg] as [Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg_general]	
	  ,[Peso Neto_total piezas de ajuste_Kgs] as [Peso Neto_total piezas de ajuste_Kgs_general]
	  ,[Peso puntas y colas reales_Kg] as [Peso puntas y colas reales_Kg_general]			
	  ,[Balance_de_Scrap_Real] as [Balance_de_Scrap_Real_general]
  FROM [cube_tkmm].[dbo].[view_union_bitacoras_silao]
  )d1

 ) v1

 UNION ALL

SELECT  
		--[id]
       [Operador]
      ,[Supervisor]
      ,[SAP Platina] 
	  ,[SAP Platina 2]
      ,[Tipo de Material]
      ,[Número de Parte de Cliente]
      ,[SAP Rollo]
      ,[Material]	  
      ,[Fecha]
      ,[Turno]
      ,[Hora]
      ,[Orden SAP]
      ,[Orden en SAP 2]
      ,[Pieza por Golpe]
      ,[N° de Rollo]
      ,CONVERT(varchar(256), CAST([Lote de rollo] AS decimal(10, 0))) AS [Lote de rollo]
      ,[Peso Etiqueta (Kg)]
      ,[Peso de regreso de rollo Real]
      ,[Peso de rollo usado ]
      ,[Peso Báscula Kgs]
      --,[N° Lote izquierdo]
      --,[N° Lote derecho]
      --,[#]
      ,[Piezas por paquete]
      ,[Total de piezas]
	  ,null AS [Peso de rollo consumido]
      ,[Numero de golpes]
      ,[Kg restante de rollo]
      ,[Peso despunte kgs#]
      ,[Peso cola Kgs#]
      ,[Porcentaje de puntas y colas]
      ,[Total de piezas de Ajustes]
      ,[Peso Bruto Kgs]
      ,[Peso Real Pieza Bruto]
      ,[Peso Real Pieza Neto]
      ,[Scrap Natural]
      ,[Peso neto SAP]
      ,[Peso Bruto SAP]
      ,[Balance de Scrap]
      ,[Column37] AS [Linea]
      ,[Column38] AS [Planta]
      ,[Column39] AS [Anio]
	  ,CONVERT(float, [Column40]) AS [Column40]
      ,[Ordenes por pieza]
      ,[Peso de rollo usado real _Kg]
      ,[Peso bruto Total piezas_Kg]
      ,[Peso NetoTotal piezas_Kg]
      ,[Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg]
      ,[Peso Neto_total piezas de ajuste_Kgs]
      ,[Peso puntas y colas reales_Kg]
      ,[Balance_de_Scrap_Real]
	    --nuevos campos
	  ,[Tipo de Material_platina2]
      ,[Número de Parte de Cliente_platina2]
	  ,[Material_platina2]
	  ,[Total de piezas_platina1]
	  ,[Total de piezas_platina2]
	  ,[Total de piezas de Ajustes_platina1]
	  ,[Total de piezas de Ajustes_platina2]
	  --platina 2
	  ,[Peso Bruto Kgs_platina2]	
	  ,[Peso Real Pieza Bruto_platina2]
	  ,[Peso Real Pieza Neto_platina2]		
	  ,[Scrap Natural_platina2]
	  ,[Peso neto SAP_platina2]
	  ,[Peso Bruto SAP_platina2]
	  ,[Balance de Scrap_platina2]	
	  ,[Peso de rollo usado real _Kg_platina2]	
	  ,[Peso bruto Total piezas_Kg_platina2]		
	  ,[Peso NetoTotal piezas_Kg_platina2]
	  ,[Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg_platina2]	
	  ,[Peso Neto_total piezas de ajuste_Kgs_platina2]
	  ,[Peso puntas y colas reales_Kg_platina2]			
	  ,[Balance_de_Scrap_Real_platina2]
	  --general
	  ,[Peso Bruto Kgs_general]	
	  ,[Peso Real Pieza Bruto_general]
	  ,[Peso Real Pieza Neto_general]		
	  ,[Scrap Natural_general]
	  ,[Peso neto SAP_general]
	  ,[Peso Bruto SAP_general]
	  ,[Balance de Scrap_general]	
	  ,[Peso de rollo usado real _Kg_general]	
	  ,[Peso bruto Total piezas_Kg_general]		
	  ,[Peso NetoTotal piezas_Kg_general]
	  ,[Scrap de ingeniería (buenas + Ajuste)_Total_Piezas_Kg_general]	
	  ,[Peso Neto_total piezas de ajuste_Kgs_general]
	  ,[Peso puntas y colas reales_Kg_general]			
	  ,[Balance_de_Scrap_Real_general]	  
  FROM [Portal_2_0].[dbo].[view_produccion_resultados])v2 
	WHERE Fecha is not null)  v3 