USE Portal_2_0
GO
IF object_id(N'SCDM_cat_clave_paises',N'U') IS NOT NULL
	BEGIN
    DROP TABLE [dbo].[SCDM_cat_clave_paises]
      PRINT '<<< SCDM_cat_clave_paises en Base de Datos:' + db_name() + 
	  ' en el Servidor:' + @@servername + ' se ha ELIMINADO! >>>'   
	END
GO

/*****************************************************************************
*  Tipo de objeto:      Table
*  Funcion: Crea una tabla para guardar los SCDM_cat_clave_paises
*  Autor :  Alfredo Xochitemol	Cruz
*  Fecha de Creación: 2023/02/13
*  Log de Mantenimiento: 
*  Date         Modified By       Description            
*  ----------   ---------------   -------------------------------------
******************************************************************************/

CREATE TABLE [dbo].[SCDM_cat_clave_paises](
	[id] [int] IDENTITY(1,1) NOT NULL,	
	[name] [varchar](30) NOT NULL,
	[iso_name] [varchar](30) NOT NULL,
	[alfa2] [varchar](2) NOT NULL,
	[alfa3] [varchar](3) NOT NULL,
	[numerico] [int] NOT NULL,
	[activo] [bit] NOT NULL DEFAULT 1,
 CONSTRAINT [PK_SCDM_cat_clave_paises_1] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

--Inserta valores

SET IDENTITY_INSERT [dbo].[SCDM_cat_clave_paises] ON 

GO
--INSERT INTO [dbo].[SCDM_cat_clave_paises] ([id], [name], [iso_name], [alfa2], [alfa3],[numerico] ) VALUES (1, ' Afganistán', 'Afganistán', 'AF', 'AFG', 4)

INSERT INTO [dbo].[SCDM_cat_clave_paises] ([id], [name], [iso_name], [alfa2], [alfa3],[numerico] ) VALUES
(1, ' Afganistán', 'Afganistán', 'AF', 'AFG', 4),
(2, ' Åland', 'Islas Åland', 'AX', 'ALA', 248),
(3, ' Albania', 'Albania', 'AL', 'ALB', 8),
(4, ' Alemania', 'Alemania', 'DE', 'DEU', 276),
(5, ' Andorra', 'Andorra', 'AD', 'AND', 20),
(6, ' Angola', 'Angola', 'AO', 'AGO', 24),
(7, ' Anguila', 'Anguila', 'AI', 'AIA', 660),
(8, ' Antártida', 'Antártida', 'AQ', 'ATA', 10),
(9, ' Antigua y Barbuda', 'Antigua y Barbuda', 'AG', 'ATG', 28),
(10, ' Arabia Saudita', 'Arabia Saudita', 'SA', 'SAU', 682),
(11, ' Argelia', 'Argelia', 'DZ', 'DZA', 12),
(12, ' Argentina', 'Argentina', 'AR', 'ARG', 32),
(13, ' Armenia', 'Armenia', 'AM', 'ARM', 51),
(14, ' Aruba', 'Aruba', 'AW', 'ABW', 533),
(15, ' Australia', 'Australia', 'AU', 'AUS', 36),
(16, ' Austria', 'Austria', 'AT', 'AUT', 40),
(17, ' Azerbaiyán', 'Azerbaiyán', 'AZ', 'AZE', 31),
(18, ' Bahamas', 'Bahamas (las)', 'BS', 'BHS', 44),
(19, ' Bangladés', 'Bangladés', 'BD', 'BGD', 50),
(20, ' Barbados', 'Barbados', 'BB', 'BRB', 52),
(21, ' Baréin', 'Baréin', 'BH', 'BHR', 48),
(22, ' Bélgica', 'Bélgica', 'BE', 'BEL', 56),
(23, ' Belice', 'Belice', 'BZ', 'BLZ', 84),
(24, ' Benín', 'Benín', 'BJ', 'BEN', 204),
(25, ' Bermudas', 'Bermudas', 'BM', 'BMU', 60),
(26, ' Bielorrusia', 'Bielorrusia', 'BY', 'BLR', 112),
(27, ' Birmania', 'Myanmar', 'MM', 'MMR', 104),
(28, ' Bolivia', 'Bolivia, Estado Plurinacional ', 'BO', 'BOL', 68),
(29, ' Bosnia y Herzegovina', 'Bosnia y Herzegovina', 'BA', 'BIH', 70),
(30, ' Botsuana', 'Botsuana', 'BW', 'BWA', 72),
(31, ' Brasil', 'Brasil', 'BR', 'BRA', 76),
(32, ' Brunéi', 'Brunéi Darussalam', 'BN', 'BRN', 96),
(33, ' Bulgaria', 'Bulgaria', 'BG', 'BGR', 100),
(34, ' Burkina Faso', 'Burkina Faso', 'BF', 'BFA', 854),
(35, ' Burundi', 'Burundi', 'BI', 'BDI', 108),
(36, ' Bután', 'Bután', 'BT', 'BTN', 64),
(37, ' Cabo Verde', 'Cabo Verde', 'CV', 'CPV', 132),
(38, ' Camboya', 'Camboya', 'KH', 'KHM', 116),
(39, ' Camerún', 'Camerún', 'CM', 'CMR', 120),
(40, ' Canadá', 'Canadá', 'CA', 'CAN', 124),
(41, ' Catar', 'Catar', 'QA', 'QAT', 634),
(42, ' Caribe Neerlandés', 'Bonaire, San Eustaquio y Saba', 'BQ', 'BES', 535),
(43, ' Chad', 'Chad', 'TD', 'TCD', 148),
(44, ' Chile', 'Chile', 'CL', 'CHL', 152),
(45, ' China', 'China', 'CN', 'CHN', 156),
(46, ' Chipre', 'Chipre', 'CY', 'CYP', 196),
(47, ' Colombia', 'Colombia', 'CO', 'COL', 170),
(48, ' Comoras', 'Comoras', 'KM', 'COM', 174),
(49, ' Corea del Norte', 'Corea (la República Democrátic', 'KP', 'PRK', 408),
(50, ' Corea del Sur', 'Corea (la República de)', 'KR', 'KOR', 410),
(51, ' Costa de Marfil', 'Côte d''Ivoire', 'CI', 'CIV', 384),
(52, ' Costa Rica', 'Costa Rica', 'CR', 'CRI', 188),
(53, ' Croacia', 'Croacia', 'HR', 'HRV', 191),
(54, ' Cuba', 'Cuba', 'CU', 'CUB', 192),
(55, ' Curazao', 'Curaçao', 'CW', 'CUW', 531),
(56, ' Dinamarca', 'Dinamarca', 'DK', 'DNK', 208),
(57, ' Dominica', 'Dominica', 'DM', 'DMA', 212),
(58, ' Ecuador', 'Ecuador', 'EC', 'ECU', 218),
(59, ' Egipto', 'Egipto', 'EG', 'EGY', 818),
(60, ' El Salvador', 'El Salvador', 'SV', 'SLV', 222),
(61, ' Emiratos Árabes Unidos', 'Emiratos Árabes Unidos (Los)', 'AE', 'ARE', 784),
(62, ' Eritrea', 'Eritrea', 'ER', 'ERI', 232),
(63, ' Eslovaquia', 'Eslovaquia', 'SK', 'SVK', 703),
(64, ' Eslovenia', 'Eslovenia', 'SI', 'SVN', 705),
(65, ' España', 'España', 'ES', 'ESP', 724),
(66, ' Estados Unidos', 'Estados Unidos (los)', 'US', 'USA', 840),
(67, ' Estonia', 'Estonia', 'EE', 'EST', 233),
(68, ' Etiopía', 'Etiopía', 'ET', 'ETH', 231),
(69, ' Filipinas', 'Filipinas (las)', 'PH', 'PHL', 608),
(70, ' Finlandia', 'Finlandia', 'FI', 'FIN', 246),
(71, ' Fiyi', 'Fiyi', 'FJ', 'FJI', 242),
(72, ' Francia', 'Francia', 'FR', 'FRA', 250),
(73, ' Gabón', 'Gabón', 'GA', 'GAB', 266),
(74, ' Gambia', 'Gambia (La)', 'GM', 'GMB', 270),
(75, ' Georgia', 'Georgia', 'GE', 'GEO', 268),
(76, ' Ghana', 'Ghana', 'GH', 'GHA', 288),
(77, ' Gibraltar', 'Gibraltar', 'GI', 'GIB', 292),
(78, ' Granada', 'Granada', 'GD', 'GRD', 308),
(79, ' Grecia', 'Grecia', 'GR', 'GRC', 300),
(80, ' Groenlandia', 'Groenlandia', 'GL', 'GRL', 304),
(81, ' Guadalupe', 'Guadalupe', 'GP', 'GLP', 312),
(82, ' Guam', 'Guam', 'GU', 'GUM', 316),
(83, ' Guatemala', 'Guatemala', 'GT', 'GTM', 320),
(84, ' Guayana Francesa', 'Guayana Francesa', 'GF', 'GUF', 254),
(85, ' Guernsey', 'Guernsey', 'GG', 'GGY', 831),
(86, ' Guinea', 'Guinea', 'GN', 'GIN', 324),
(87, ' Guinea-Bisáu', 'Guinea-Bisáu', 'GW', 'GNB', 624),
(88, ' Guinea Ecuatorial', 'Guinea Ecuatorial', 'GQ', 'GNQ', 226),
(89, ' Guyana', 'Guyana', 'GY', 'GUY', 328),
(90, ' Haití', 'Haití', 'HT', 'HTI', 332),
(91, ' Honduras', 'Honduras', 'HN', 'HND', 340),
(92, ' Hong Kong', 'Hong Kong', 'HK', 'HKG', 344),
(93, ' Hungría', 'Hungría', 'HU', 'HUN', 348),
(94, ' India', 'India', 'IN', 'IND', 356),
(95, ' Indonesia', 'Indonesia', 'ID', 'IDN', 360),
(96, ' Irak', 'Irak', 'IQ', 'IRQ', 368),
(97, ' Irán', 'Irán (la República Islámica de', 'IR', 'IRN', 364),
(98, ' Irlanda', 'Irlanda', 'IE', 'IRL', 372),
(99, ' Isla Bouvet', 'Isla Bouvet', 'BV', 'BVT', 74),
(100, ' Isla de Man', 'Isla de Man', 'IM', 'IMN', 833),
(101, ' Isla de Navidad', 'Isla de Navidad', 'CX', 'CXR', 162),
(102, ' Norfolk', 'Isla Norfolk', 'NF', 'NFK', 574),
(103, ' Islandia', 'Islandia', 'IS', 'ISL', 352),
(104, ' Islas Caimán', 'Islas Caimán (las)', 'KY', 'CYM', 136),
(105, ' Islas Cocos', 'Islas Cocos (Keeling)', 'CC', 'CCK', 166),
(106, ' Islas Cook', 'Islas Cook (las)', 'CK', 'COK', 184),
(107, ' Islas Feroe', 'Islas Feroe (las)', 'FO', 'FRO', 234),
(108, ' Islas Georgias del Sur y Sand', 'Georgia del sur y las islas sa', 'GS', 'SGS', 239),
(109, ' Islas Heard y McDonald', 'Isla Heard e Islas McDonald', 'HM', 'HMD', 334),
(110, ' Islas Malvinas', 'Islas Malvinas [Falkland] (las', 'FK', 'FLK', 238),
(111, ' Islas Marianas del Norte', 'Islas Marianas del Norte (las)', 'MP', 'MNP', 580),
(112, ' Islas Marshall', 'Islas Marshall (las)', 'MH', 'MHL', 584),
(113, ' Islas Pitcairn', 'Pitcairn', 'PN', 'PCN', 612),
(114, ' Islas Salomón', 'Islas Salomón (las)', 'SB', 'SLB', 90),
(115, ' Islas Turcas y Caicos', 'Islas Turcas y Caicos (las)', 'TC', 'TCA', 796),
(116, ' Islas ultramarinas de Estados', 'Islas de Ultramar Menores de E', 'UM', 'UMI', 581),
(117, ' Islas Vírgenes Británicas', 'Islas Vírgenes (Británicas)', 'VG', 'VGB', 92),
(118, ' Islas Vírgenes de los Estados', 'Islas Vírgenes (EE.UU.)', 'VI', 'VIR', 850),
(119, ' Israel', 'Israel', 'IL', 'ISR', 376),
(120, ' Italia', 'Italia', 'IT', 'ITA', 380),
(121, ' Jamaica', 'Jamaica', 'JM', 'JAM', 388),
(122, ' Japón', 'Japón', 'JP', 'JPN', 392),
(123, ' Jersey', 'Jersey', 'JE', 'JEY', 832),
(124, ' Jordania', 'Jordania', 'JO', 'JOR', 400),
(125, ' Kazajistán', 'Kazajistán', 'KZ', 'KAZ', 398),
(126, ' Kenia', 'Kenia', 'KE', 'KEN', 404),
(127, ' Kirguistán', 'Kirguistán', 'KG', 'KGZ', 417),
(128, ' Kiribati', 'Kiribati', 'KI', 'KIR', 296),
(129, ' Kuwait', 'Kuwait', 'KW', 'KWT', 414),
(130, ' Laos', 'Lao, (la) República Democrátic', 'LA', 'LAO', 418),
(131, ' Lesoto', 'Lesoto', 'LS', 'LSO', 426),
(132, ' Letonia', 'Letonia', 'LV', 'LVA', 428),
(133, ' Líbano', 'Líbano', 'LB', 'LBN', 422),
(134, ' Liberia', 'Liberia', 'LR', 'LBR', 430),
(135, ' Libia', 'Libia', 'LY', 'LBY', 434),
(136, ' Liechtenstein', 'Liechtenstein', 'LI', 'LIE', 438),
(137, ' Lituania', 'Lituania', 'LT', 'LTU', 440),
(138, ' Luxemburgo', 'Luxemburgo', 'LU', 'LUX', 442),
(139, ' Macao', 'Macao', 'MO', 'MAC', 446),
(140, ' Madagascar', 'Madagascar', 'MG', 'MDG', 450),
(141, ' Malasia', 'Malasia', 'MY', 'MYS', 458),
(142, ' Malaui', 'Malaui', 'MW', 'MWI', 454),
(143, ' Maldivas', 'Maldivas', 'MV', 'MDV', 462),
(144, ' Malí', 'Malí', 'ML', 'MLI', 466),
(145, ' Malta', 'Malta', 'MT', 'MLT', 470),
(146, ' Marruecos', 'Marruecos', 'MA', 'MAR', 504),
(147, ' Martinica', 'Martinica', 'MQ', 'MTQ', 474),
(148, ' Mauricio', 'Mauricio', 'MU', 'MUS', 480),
(149, ' Mauritania', 'Mauritania', 'MR', 'MRT', 478),
(150, ' Mayotte', 'Mayotte', 'YT', 'MYT', 175),
(151, ' México', 'México', 'MX', 'MEX', 484),
(152, ' Micronesia', 'Micronesia (los Estados Federa', 'FM', 'FSM', 583),
(153, ' Moldavia', 'Moldavia (la República de)', 'MD', 'MDA', 498),
(154, ' Mónaco', 'Mónaco', 'MC', 'MCO', 492),
(155, ' Mongolia', 'Mongolia', 'MN', 'MNG', 496),
(156, ' Montenegro', 'Montenegro', 'ME', 'MNE', 499),
(157, ' Montserrat', 'Montserrat', 'MS', 'MSR', 500),
(158, ' Mozambique', 'Mozambique', 'MZ', 'MOZ', 508),
(159, ' Namibia', 'Namibia', 'NA', 'NAM', 516),
(160, ' Nauru', 'Nauru', 'NR', 'NRU', 520),
(161, ' Nepal', 'Nepal', 'NP', 'NPL', 524),
(162, ' Nicaragua', 'Nicaragua', 'NI', 'NIC', 558),
(163, ' Níger', 'Níger (el)', 'NE', 'NER', 562),
(164, ' Nigeria', 'Nigeria', 'NG', 'NGA', 566),
(165, ' Niue', 'Niue', 'NU', 'NIU', 570),
(166, ' Noruega', 'Noruega', 'NO', 'NOR', 578),
(167, ' Nueva Caledonia', 'Nueva Caledonia', 'NC', 'NCL', 540),
(168, ' Nueva Zelanda', 'Nueva Zelanda', 'NZ', 'NZL', 554),
(169, ' Omán', 'Omán', 'OM', 'OMN', 512),
(170, ' Países Bajos', 'Países Bajos (los)', 'NL', 'NLD', 528),
(171, ' Pakistán', 'Pakistán', 'PK', 'PAK', 586),
(172, ' Palaos', 'Palaos', 'PW', 'PLW', 585),
(173, ' Palestina', 'Palestina, Estado de', 'PS', 'PSE', 275),
(174, ' Panamá', 'Panamá', 'PA', 'PAN', 591),
(175, ' Papúa Nueva Guinea', 'Papúa Nueva Guinea', 'PG', 'PNG', 598),
(176, ' Paraguay', 'Paraguay', 'PY', 'PRY', 600),
(177, ' Perú', 'Perú', 'PE', 'PER', 604),
(178, ' Polinesia Francesa', 'Polinesia Francesa', 'PF', 'PYF', 258),
(179, ' Polonia', 'Polonia', 'PL', 'POL', 616),
(180, ' Portugal', 'Portugal', 'PT', 'PRT', 620),
(181, ' Puerto Rico', 'Puerto Rico', 'PR', 'PRI', 630),
(182, ' Reino Unido', 'Reino Unido (el)', 'GB', 'GBR', 826),
(183, ' República Centroafricana', 'República Centroafricana (la)', 'CF', 'CAF', 140),
(184, ' República Checa', 'República Checa (la)', 'CZ', 'CZE', 203),
(185, ' Macedonia', 'Macedonia (la antigua Repúblic', 'MK', 'MKD', 807),
(186, ' República del Congo', 'Congo', 'CG', 'COG', 178),
(187, ' República Democrática del Con', 'Congo (la República Democrátic', 'CD', 'COD', 180),
(188, ' República Dominicana', 'República Dominicana (la)', 'DO', 'DOM', 214),
(189, ' Reunión', 'Reunión', 'RE', 'REU', 638),
(190, ' Ruanda', 'Ruanda', 'RW', 'RWA', 646),
(191, ' Rumania', 'Rumania', 'RO', 'ROU', 642),
(192, ' Rusia', 'Rusia, (la) Federación de', 'RU', 'RUS', 643),
(193, ' República Árabe Saharaui Demo', 'Sahara Occidental', 'EH', 'ESH', 732),
(194, ' Samoa', 'Samoa', 'WS', 'WSM', 882),
(195, ' Samoa Americana', 'Samoa Americana', 'AS', 'ASM', 16),
(196, ' San Bartolomé', 'San Bartolomé', 'BL', 'BLM', 652),
(197, ' San Cristóbal y Nieves', 'San Cristóbal y Nieves', 'KN', 'KNA', 659),
(198, ' San Marino', 'San Marino', 'SM', 'SMR', 674),
(199, ' San Martín', 'San Martín (parte francesa)', 'MF', 'MAF', 663),
(200, ' San Pedro y Miquelón', 'San Pedro y Miquelón', 'PM', 'SPM', 666),
(201, ' San Vicente y las Granadinas', 'San Vicente y las Granadinas', 'VC', 'VCT', 670),
(202, ' Santa Elena, Ascensión y Tris', 'Santa Helena, Ascensión y Tris', 'SH', 'SHN', 654),
(203, ' Santa Lucía', 'Santa Lucía', 'LC', 'LCA', 662),
(204, ' Santo Tomé y Príncipe', 'Santo Tomé y Príncipe', 'ST', 'STP', 678),
(205, ' Senegal', 'Senegal', 'SN', 'SEN', 686),
(206, ' Serbia', 'Serbia', 'RS', 'SRB', 688),
(207, ' Seychelles', 'Seychelles', 'SC', 'SYC', 690),
(208, ' Sierra Leona', 'Sierra leona', 'SL', 'SLE', 694),
(209, ' Singapur', 'Singapur', 'SG', 'SGP', 702),
(210, ' Sint Maarten', 'Sint Maarten (parte holandesa)', 'SX', 'SXM', 534),
(211, ' Siria', 'Siria, (la) República Árabe', 'SY', 'SYR', 760),
(212, ' Somalia', 'Somalia', 'SO', 'SOM', 706),
(213, ' Sri Lanka', 'Sri Lanka', 'LK', 'LKA', 144),
(214, ' Suazilandia', 'Suazilandia', 'SZ', 'SWZ', 748),
(215, ' Sudáfrica', 'Sudáfrica', 'ZA', 'ZAF', 710),
(216, ' Sudán', 'Sudán (el)', 'SD', 'SDN', 729),
(217, ' Sudán del Sur', 'Sudán del Sur', 'SS', 'SSD', 728),
(218, ' Suecia', 'Suecia', 'SE', 'SWE', 752),
(219, '  Suiza', 'Suiza', 'CH', 'CHE', 756),
(220, ' Surinam', 'Surinam', 'SR', 'SUR', 740),
(221, ' Svalbard y Jan Mayen', 'Svalbard y Jan Mayen', 'SJ', 'SJM', 744),
(222, ' Tailandia', 'Tailandia', 'TH', 'THA', 764),
(223, ' República de China', 'Taiwán (Provincia de China)', 'TW', 'TWN', 158),
(224, ' Tanzania', 'Tanzania, República Unida de', 'TZ', 'TZA', 834),
(225, ' Tayikistán', 'Tayikistán', 'TJ', 'TJK', 762),
(226, ' Territorio Británico del Océa', 'Territorio Británico del Océan', 'IO', 'IOT', 86),
(227, ' Tierras Australes y Antártica', 'Territorios Australes Francese', 'TF', 'ATF', 260),
(228, ' Timor Oriental', 'Timor-Leste', 'TL', 'TLS', 626),
(229, ' Togo', 'Togo', 'TG', 'TGO', 768),
(230, ' Tokelau', 'Tokelau', 'TK', 'TKL', 772),
(231, ' Tonga', 'Tonga', 'TO', 'TON', 776),
(232, ' Trinidad y Tobago', 'Trinidad y Tobago', 'TT', 'TTO', 780),
(233, ' Túnez', 'Túnez', 'TN', 'TUN', 788),
(234, ' Turkmenistán', 'Turkmenistán', 'TM', 'TKM', 795),
(235, ' Turquía', 'Turquía', 'TR', 'TUR', 792),
(236, ' Tuvalu', 'Tuvalu', 'TV', 'TUV', 798),
(237, ' Ucrania', 'Ucrania', 'UA', 'UKR', 804),
(238, ' Uganda', 'Uganda', 'UG', 'UGA', 800),
(239, ' Uruguay', 'Uruguay', 'UY', 'URY', 858),
(240, ' Uzbekistán', 'Uzbekistán', 'UZ', 'UZB', 860),
(241, ' Vanuatu', 'Vanuatu', 'VU', 'VUT', 548),
(242, ' Ciudad del Vaticano', 'Santa Sede [Estado de la Ciuda', 'VA', 'VAT', 336),
(243, ' Venezuela', 'Venezuela, República Bolivaria', 'VE', 'VEN', 862),
(244, ' Vietnam', 'Viet Nam', 'VN', 'VNM', 704),
(245, ' Wallis y Futuna', 'Wallis y Futuna', 'WF', 'WLF', 876),
(246, ' Yemen', 'Yemen', 'YE', 'YEM', 887),
(247, ' Yibuti', 'Yibuti', 'DJ', 'DJI', 262),
(248, ' Zambia', 'Zambia', 'ZM', 'ZMB', 894),
(249, ' Zimbabue', 'Zimbabue', 'ZW', 'ZWE', 716);


GO

SET IDENTITY_INSERT [dbo].[SCDM_cat_clave_paises] OFF
	  
IF object_id(N'SCDM_cat_clave_paises',N'U') IS NOT NULL
	BEGIN
		PRINT '<<< SCDM_cat_clave_paises en Base de Datos:' + db_name() + 
		' en el Servidor:' + @@servername + ' se ha creado con exito! >>>'
	END
ELSE
	BEGIN
	      PRINT '<<< No ha sido posible crear la tabla SCDM_cat_clave_paises  ' +
		  'en la Base de Datos: ' + db_name() + ' en el Servidor: ' + @@servername + '  >>>'
	END
	
SET ANSI_PADDING OFF
GO
